name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  cocoapods:
    name: CocoaPods Lint & Danger
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle install
      - run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: PODSPEC=1 ./script/travis-script-macos

  xcode:
    name: Xcode ${{ matrix.xcode }} (${{ matrix.platform }})
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.5]
        platform: ["macos", "ios", "tvos"]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: PLATFORM=${{ matrix.platform }} ./script/travis-script-macos
      - if: ${{ matrix.platform == 'macos' }}
        run: PLATFORM=${{ matrix.platform }}_static ./script/travis-script-macos

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.5]
      fail-fast: false
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app"
    steps:
      - uses: actions/checkout@v2
      - run: PLATFORM=swiftpm ./script/travis-script-macos
