//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface CKDownloadQueue : CKServiceInterface {
	NSMutableDictionary *_downloadQueueObservers;
	NSMutableDictionary *_downloadsByItemID;
	NSLock *_downloadsLock;
	id _observerToken NS_AVAILABLE_MAC(13);
	CKDownloadQueueClient *_sharedObserver;
	NSLock *_tokenLock NS_AVAILABLE_MAC(13);
}

+ (instancetype)sharedDownloadQueue;

@property(retain, nonatomic) NSMutableDictionary *downloadQueueObservers;
@property(readonly, nonatomic) NSArray *downloads;
@property(retain, nonatomic) CKDownloadQueueClient *sharedObserver;

- (void)addDownload:(SSDownload *)download;
- (id<CKDownloadQueueObserver>)addObserver:(id<CKDownloadQueueObserver>)observer;
- (id<CKDownloadQueueObserver>)addObserver:(id<CKDownloadQueueObserver>)observer forDownloadTypes:(long long)downloadTypes;
- (id<CKDownloadQueueObserver>)addObserverForDownloadTypes:(long long)downloadTypes withBlock:(UnknownBlock *)block;
- (BOOL)cacheReceiptDataForDownload:(SSDownload *)download;
- (void)cancelDownload:(SSDownload *)download promptToConfirm:(BOOL)promptToConfirm askToDelete:(BOOL)askToDelete;
- (void)checkStoreDownloadQueueForAccount:(ISStoreAccount *)account;
- (void)connectionWasInterrupted;
- (SSDownload *)downloadForItemIdentifier:(unsigned long long)identifier;
- (void)fetchIconForItemIdentifier:(unsigned long long)identifier atURL:(NSURL *)url replyBlock:(UnknownBlock *)block;
- (instancetype)initWithStoreClient:(ISStoreClient *)client;
- (void)lockApplicationsForBundleID:(NSString *)bundleID;
- (void)lockedApplicationTriedToLaunchAtPath:(NSString *)path;
- (void)pauseDownloadWithItemIdentifier:(unsigned long long)identifier;
- (void)performedIconAnimationForDownloadWithIdentifier:(unsigned long long)identifier;
- (void)removeDownloadWithItemIdentifier:(unsigned long long)identifier;
- (void)removeObserver:(id<CKDownloadQueueObserver>)observer;
- (void)resumeDownloadWithItemIdentifier:(unsigned long long)identifier;
- (void)unlockApplicationsWithBundleIdentifier:(NSString *)bundleID;

@end

NS_ASSUME_NONNULL_END
