//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface CKDownloadQueue : CKServiceInterface {
	NSMutableDictionary *_downloadQueueObservers;
	NSMutableDictionary *_downloadsByItemID;
	NSLock *_downloadsLock;
	CKDownloadQueueClient *_sharedObserver;
}

+ (instancetype)sharedDownloadQueue;

@property(retain, nonatomic) NSMutableDictionary *downloadQueueObservers; // @synthesize downloadQueueObservers=_downloadQueueObservers;
@property(readonly, nonatomic) NSArray *downloads; // @dynamic downloads;
@property(retain, nonatomic) CKDownloadQueueClient *sharedObserver; // @synthesize sharedObserver=_sharedObserver;

- (void)addDownload:(SSDownload *)download;
- (id<CKDownloadQueueObserver>)addObserver:(id<CKDownloadQueueObserver>)observer;
- (id<CKDownloadQueueObserver>)addObserver:(id<CKDownloadQueueObserver>)observer forDownloadTypes:(long long)downloadTypes;
- (id<CKDownloadQueueObserver>)addObserverForDownloadTypes:(long long)downloadTypes withBlock:(UnknownBlock *)block;
- (BOOL)cacheReceiptDataForDownload:(SSDownload *)download;
- (void)cancelDownload:(SSDownload *)download promptToConfirm:(BOOL)promptToConfirm askToDelete:(BOOL)askToDelete;
- (void)checkStoreDownloadQueueForAccount:(ISStoreAccount *)account;
- (void)connectionWasInterrupted;
- (SSDownload *)downloadForItemIdentifier:(unsigned long long)identifier;
- (void)fetchIconForItemIdentifier:(unsigned long long)identifier atURL:(NSURL *)url replyBlock:(UnknownBlock *)block;
- (instancetype)initWithStoreClient:(ISStoreClient *)client;
- (void)lockApplicationsForBundleID:(NSString *)bundleID;
- (void)lockedApplicationTriedToLaunchAtPath:(NSString *)path;
- (void)pauseDownloadWithItemIdentifier:(unsigned long long)identifier;
- (void)performedIconAnimationForDownloadWithIdentifier:(unsigned long long)identifier;
- (void)removeDownloadWithItemIdentifier:(unsigned long long)identifier;
- (void)removeObserver:(id<CKDownloadQueueObserver>)observer;
- (void)resumeDownloadWithItemIdentifier:(unsigned long long)identifier;
- (void)unlockApplicationsWithBundleIdentifier:(NSString *)bundleID;

@end

NS_ASSUME_NONNULL_END
