//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

typedef void (^SSPurchaseCompletion)(SSPurchase * _Nullable purchase, BOOL completed, NSError * _Nullable error, SSPurchaseResponse * _Nullable response);

@interface CKPurchaseController : CKServiceInterface {
	NSArray *_adoptionEligibleItems;
	NSNumber *_adoptionErrorNumber;
	NSNumber *_adoptionServerStatus;
	UnknownBlock *_dialogHandler;
	NSMutableArray *_purchases;
	NSMutableArray *_rejectedPurchases;
}

+ (void)setNeedsSilentMachineAuthorization:(BOOL)needsSilentMachineAuthorization;
+ (instancetype)sharedPurchaseController;

@property(copy) UnknownBlock *dialogHandler;

- (void)_performVPPReceiptRenewal;
- (BOOL)adoptionCompletedForBundleID:(NSString *)bundleID;
- (void)cancelPurchaseWithProductID:(NSNumber *)productID;
- (void)checkServerDownloadQueue;
- (void)performPurchase:(SSPurchase *)purchase withOptions:(unsigned long long)options completionHandler:(nullable SSPurchaseCompletion)handler;
- (SSPurchase *)purchaseInProgressForProductID:(NSNumber *)productID;
- (NSArray<SSPurchase *> *)purchasesInProgress;
- (void)resumeDownloadForPurchasedProductID:(NSNumber *)productID;
- (void)startPurchases:(NSArray<SSPurchase *> *)purchases shouldStartDownloads:(BOOL)shouldStartDownloads eventHandler:(UnknownBlock *)handler;
- (void)startPurchases:(NSArray<SSPurchase *> *)purchases withOptions:(unsigned long long)options completionHandler:(UnknownBlock *)handler;

@end

NS_ASSUME_NONNULL_END
