//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

typedef void (^SSPurchaseCompletion)(SSPurchase * _Nullable purchase, BOOL completed, NSError * _Nullable error, SSPurchaseResponse * _Nullable response);

@interface CKPurchaseController : CKServiceInterface {
	NSArray *_adoptionEligibleItems;
	NSNumber *_adoptionErrorNumber;
	NSNumber *_adoptionServerStatus;
	UnknownBlock *_dialogHandler;
	NSMutableArray *_purchases;
	NSMutableArray *_rejectedPurchases;
}

+ (void)setNeedsSilentMachineAuthorization:(BOOL)arg1;
+ (instancetype)sharedPurchaseController;

@property(copy) UnknownBlock *dialogHandler; // @synthesize dialogHandler=_dialogHandler;

- (void)_performVPPReceiptRenewal;
- (BOOL)adoptionCompletedForBundleID:(id)arg1;
- (void)cancelPurchaseWithProductID:(id)arg1;
- (void)checkServerDownloadQueue;
- (void)performPurchase:(SSPurchase *)purchase withOptions:(unsigned long long)arg2 completionHandler:(SSPurchaseCompletion _Nullable)completionHandler;
- (id)purchaseInProgressForProductID:(id)arg1;
- (id)purchasesInProgress;
- (void)resumeDownloadForPurchasedProductID:(id)arg1;
- (void)startPurchases:(id)arg1 shouldStartDownloads:(BOOL)arg2 eventHandler:(UnknownBlock *)arg3;
- (void)startPurchases:(id)arg1 withOptions:(unsigned long long)arg2 completionHandler:(UnknownBlock *)arg3;

//- (void).cxx_destruct;

@end

NS_ASSUME_NONNULL_END
