//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

typedef void (^SSPurchaseCompletion)(SSPurchase * _Nullable purchase, BOOL completed, NSError * _Nullable error, SSPurchaseResponse * _Nullable response);

@interface CKPurchaseController : CKServiceInterface {
	NSArray *_adoptionEligibleItems;
	NSNumber *_adoptionErrorNumber;
	NSNumber *_adoptionServerStatus;
	UnknownBlock *_dialogHandler;
	NSMutableArray *_purchases;
	NSMutableArray *_rejectedPurchases;
}

+ (void)setNeedsSilentMachineAuthorization:(BOOL)needsSilentMachineAuthorization;
+ (instancetype)sharedPurchaseController;

@property(copy) UnknownBlock *dialogHandler; // @synthesize dialogHandler=_dialogHandler;

- (void)_performVPPReceiptRenewal;
- (BOOL)adoptionCompletedForBundleID:(NSString *)bundleID;
- (void)cancelPurchaseWithProductID:(NSNumber *)productID;
- (void)checkServerDownloadQueue;
- (void)performPurchase:(SSPurchase *)purchase withOptions:(unsigned long long)options completionHandler:(nullable SSPurchaseCompletion)handler;
- (SSPurchase *)purchaseInProgressForProductID:(NSNumber *)productID;
- (NSArray<SSPurchase *> *)purchasesInProgress;
- (void)resumeDownloadForPurchasedProductID:(NSNumber *)productID;
- (void)startPurchases:(NSArray<SSPurchase *> *)purchases shouldStartDownloads:(BOOL)shouldStartDownloads eventHandler:(UnknownBlock *)handler;
- (void)startPurchases:(NSArray<SSPurchase *> *)purchases withOptions:(unsigned long long)options completionHandler:(UnknownBlock *)handler;

@end

NS_ASSUME_NONNULL_END
