//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.643, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.1, SDK: 26.1, Tool: ld (1230.3)
// - LC_SOURCE_VERSION: 716.1.1.0.0
//

@interface CKServiceInterface : ISServiceProxy

@end
