//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.646, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
// - LC_SOURCE_VERSION: 716.2.2.0.0
//

@interface CKServiceInterface : ISServiceProxy

@end
