//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.707, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.5, SDK: 26.5, Tool: ld (1267)
// - LC_SOURCE_VERSION: 716.4.2.0.0
//

@interface CKServiceInterface : ISServiceProxy

@end
