---
version: 2
updates:
- package-ecosystem: github-actions
  schedule:
    interval: daily
  directory: /
  labels: [dependencies]
  commit-message:
    prefix: ⬆️
    include: scope
- package-ecosystem: swift
  schedule:
    interval: daily
  directory: /
  labels: [dependencies]
  commit-message:
    prefix: ⬆️
    include: scope
