# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/main/schema/markdownlint-cli2-config-schema.json
#
# .markdownlint-cli2.yaml
# mas
#
# markdownlint-cli2 0.20.0 / markdownlint 0.40.0
#
---
gitignore: true
noBanner: true
noProgress: true
config:
  blanks-around-fences:
    list_items: false
  code-block-style:
    style: fenced
  code-fence-style:
    style: backtick
  emphasis-style:
    style: underscore
  fenced-code-language:
    allowed_languages: [console, shell]
    language_only: true
  heading-style:
    style: atx
  hr-style:
    style: ---
  line-length:
    stern: true
  link-image-style:
    shortcut: false
    url_inline: false
  no-hard-tabs:
    code_blocks: false
    spaces_per_tab: 2
  no-inline-html:
    allowed_elements: [details, h1, summary]
  no-trailing-spaces:
    code_blocks: true
    strict: true
  ol-prefix:
    style: ordered
  proper-names:
    names: [mas]
  reference-links-images:
    shortcut_syntax: true
  strong-style:
    style: asterisk
  table-column-style:
    style: aligned
  table-pipe-style:
    style: leading_and_trailing
  ul-style:
    style: dash
