#
# .swiftlint.yml
# mas
#
# SwiftLint 0.61.0
#
---
excluded:
- .build/
- .idea/
- .swiftpm/
opt_in_rules:
- all
analyzer_rules:
- all
disabled_rules: # Never enable
- contrasted_opening_brace
- explicit_acl
- explicit_enum_raw_value
- explicit_self
- explicit_top_level_acl
- explicit_type_interface
- file_header
- no_extension_access_modifier
- no_grouping_extension
- no_magic_numbers
- prefixed_toplevel_constant
- sorted_enum_cases
- strict_fileprivate
- vertical_whitespace_between_cases
- void_function_in_ternary
attributes:
  always_on_line_above: ['@MainActor', '@OptionGroup', '@objc']
closure_body_length:
  warning: 35
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 13
deployment_target:
  macOS_deployment_target: 10.15
  macOSApplicationExtension_deployment_target: 10.15
  iOS_deployment_target: 99
  iOSApplicationExtension_deployment_target: 99
  tvOS_deployment_target: 99
  tvOSApplicationExtension_deployment_target: 99
  watchOS_deployment_target: 99
  watchOSApplicationExtension_deployment_target: 99
explicit_init:
  include_bare_init: true
file_length:
  ignore_comment_only_lines: true
file_name:
  excluded: [SpotlightInstalledApps.swift]
file_types_order:
  order:
  - main_type
  - supporting_type
  - extension
  - preview_provider
  - library_content_provider
function_body_length:
  warning: 80
indentation_width:
  indentation_width: 2
  include_multiline_strings: false
line_length:
  ignores_multiline_strings: true
multiline_arguments:
  first_argument_location: next_line
non_optional_string_data_conversion:
  include_variables: true
number_separator:
  minimum_length: 6
opening_brace:
  ignore_multiline_statement_conditions: true
operator_usage_whitespace:
  skip_aligned_constants: false
prefer_key_path:
  restrict_to_standard_functions: false
private_over_fileprivate:
  validate_extensions: true
redundant_type_annotation:
  consider_default_literal_types_redundant: true
trailing_comma:
  mandatory_comma: true
trailing_whitespace:
  ignores_comments: false
type_contents_order:
  order:
  - case
  - associated_type
  - type_alias
  - subtype
  - type_property
  - instance_property
  - ib_inspectable
  - ib_outlet
  - initializer
  - deinitializer
  - type_method
  - view_life_cycle_method
  - ib_action
  - other_method
  - subscript
unneeded_override:
  affect_initializers: true
unused_import:
  require_explicit_imports: true
  allowed_transitive_imports:
  - module: Darwin
    allowed_transitive_imports:
    - _DarwinFoundation1
    - _DarwinFoundation2
    - _DarwinFoundation3
    - _limits
    - _math
    - _signal
    - _stdio
    - DarwinFoundation
    - sys_types
    - unistd
  - module: Swift
    allowed_transitive_imports:
    - _Concurrency
