#
# .swiftlint.yml
# mas
#
# https://github.com/realm/SwiftLint#configuration
#
---
opt_in_rules:
  - all
disabled_rules:
  # eventually enable
  - file_header
  - one_declaration_per_file
  - trailing_comma
  # never enable
  - contrasted_opening_brace
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - inert_defer
  - no_extension_access_modifier
  - no_grouping_extension
  - prefixed_toplevel_constant
  - sorted_enum_cases
  - unused_capture_list
  - vertical_whitespace_between_cases
file_name:
  excluded: [Finder.swift, Utilities.swift]
file_types_order:
  order:
    [
      [main_type],
      [supporting_type],
      [extension],
      [preview_provider],
      [library_content_provider],
    ]
number_separator:
  minimum_length: 6
type_contents_order:
  order:
    [
      [case],
      [type_alias, associated_type],
      [subtype],
      [type_property],
      [instance_property],
      [ib_inspectable],
      [ib_outlet],
      [initializer],
      [deinitializer],
      [type_method],
      [view_life_cycle_method],
      [ib_action],
      [other_method],
      [subscript],
    ]
