#
# .swiftlint.yml
# mas
#
# SwiftLint 0.61.0
#
---
excluded:
- .build/
- .idea/
- .swiftpm/
opt_in_rules:
- all
analyzer_rules:
- all
disabled_rules:
# Never enable
- contrasted_opening_brace
- explicit_acl
- explicit_enum_raw_value
- explicit_self
- explicit_top_level_acl
- explicit_type_interface
- no_extension_access_modifier
- no_grouping_extension
- no_magic_numbers
- prefixed_toplevel_constant
- sorted_enum_cases
- strict_fileprivate
- vertical_whitespace_between_cases
- void_function_in_ternary
attributes:
  always_on_line_above: ['@MainActor', '@OptionGroup']
closure_body_length:
  warning: 40
cyclomatic_complexity:
  warning: 11
file_types_order:
  order:
  - main_type
  - supporting_type
  - extension
  - preview_provider
  - library_content_provider
function_body_length:
  warning: 75
indentation_width:
  include_multiline_strings: false
number_separator:
  minimum_length: 6
opening_brace:
  ignore_multiline_statement_conditions: true
trailing_comma:
  mandatory_comma: true
type_contents_order:
  order:
  - case
  - associated_type
  - type_alias
  - subtype
  - type_property
  - instance_property
  - ib_inspectable
  - ib_outlet
  - initializer
  - deinitializer
  - type_method
  - view_life_cycle_method
  - ib_action
  - other_method
  - subscript
