#
# .swiftlint.yml
# mas
#
# SwiftLint 0.59.1
#
# https://github.com/realm/SwiftLint#configuration
#
---
opt_in_rules:
- file_header
- file_name
file_header:
  required_pattern: |
    \/\/
    \/\/ SWIFTLINT_CURRENT_FILENAME
    \/\/ mas
    \/\/
    \/\/ Created by (.+?) on (20\d{2})-\d{2}-\d{2}\.
    \/\/ Copyright © \2 (?:mas-cli|\1)\. All rights reserved\.
    \/\/
file_name:
  excluded: [Finder.swift, SpotlightInstalledApps.swift]
