---
name: Bug Report
description: Report a bug.
labels: [\U0001F41B bug]
body:
- type: markdown
  attributes:
    value: |
      # Configuration
- type: textarea
  id: config
  attributes:
    label: mas config
    description: Output of `mas config --markdown`
    value: |
      <!--
      If `mas config --markdown` runs without error, replace the contents of this text area with its output.

      Otherwise, your mas version does not have `mas config`, so provide the following:
      -->

      ### mas version (output of `mas version`)
      <!--Example: "1.8.8"-->


      ### macOS version (output of `sw_vers -productVersion`)
      <!--Example: "15.1.1"-->


      ### macOS build (output of `sw_vers -buildVersion`)
      <!--Example: "24B2091"-->


      ### CPU (output of `sysctl -n machdep.cpu.brand_string`)
      <!--Example: "Apple M1"-->


      ### Installation method
      <!--Delete the incorrect ones.-->

      Homebrew core (via `brew install mas`)
      Homebrew custom tap (via `brew install mas-cli/tap/mas`)
      GitHub Releases (from <https://github.com/mas-cli/mas/releases>)
      Built from source (provide info about build)
      Other
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Issue
- type: textarea
  id: description
  attributes:
    label: Bug description
    description: Expected & actual output; other pertinent info
  validations:
    required: true
- type: textarea
  id: reproduction
  attributes:
    label: Steps to reproduce
    description: |
      Copied, pasted & formatted commands & output in console blocks (as instructed below); instructions; screenshots
    value: |
      ```console

      ```
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Console command & output formatting instructions

      Provide console commands & output as copied, pasted & formatted text, instead of as screenshots.

      If long descriptive text or screenshots of dialogs or apps are necessary, provide them between console blocks.

      Format commands & output as follows (where `…` is a placeholder):

      - Use a console block: start with ```` ```console ````, end with ```` ``` ````, each on its own line
      - Prefix each non-console step (or comment) with two hashes & a space: `## …`
      - Remove custom shell prompts; instead, prefix each console command with a dollar sign & a space: `$ …`
      - Prefix each output line beginning with `#`, `$`, `%`, or `>` with an additional instance of that <!--
        --> character: `##…`, `$$…`, `%%…`, or `>>…`
      - Write all other output lines without any prefix: `…`

      e.g.:

      ````text
      ```console
      ## In the Mac App Store GUI, click on…
      $ mas list
      123  App 1  (4.5.6)
      124  App 2  (10.2)
      $ mas outdated
      123 App 1 (4.5.6 -> 4.5.7)
      ```
      ````
