---
name: Bug Report
description: Report a bug.
labels: [\U0001F41B bug]
body:
- type: textarea
  id: config
  attributes:
    label: Configuration
    placeholder: Output of `mas config`
    render: text
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Bug description
    placeholder: |
      Bug description

      Include expected & actual output, plus other pertinent info

      Instead of screenshots, prefer pasting copied commands & output into console blocks, formatted as instructed below
  validations:
    required: true
- type: textarea
  id: reproduction
  attributes:
    label: Steps to reproduce
    placeholder: |
      Steps to reproduce

      Instead of screenshots, prefer pasting copied commands & output into console blocks, formatted as instructed below
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Console command & output formatting instructions

      Provide console commands & output as copied, pasted & formatted text, instead of as screenshots.

      If long descriptive text or screenshots of dialogs or apps are necessary, provide them between console blocks.

      Format commands & output as follows (where `…` is a placeholder):

      - Use a console block: start with ```` ```console ````, end with ```` ``` ````, each on its own line
      - Prefix each non-console step (or comment) with two hashes & a space: `## …`
      - Remove shell prompts; instead, prefix each console command with a dollar sign & a space: `$ …`
      - Prefix each output line beginning with `#`, `$`, `%`, or `>` with an additional instance of that <!--
        --> character: `##…`, `$$…`, `%%…`, or `>>…`
      - Write all other output lines without any prefix: `…`

      e.g.:

      ````text
      ```console
      ## In the Mac App Store GUI, click on…
      $ mas list
      123  App 1  (4.5.6)
      124  App 2  (10.2)
      $ mas outdated
      123 App 1 (4.5.6 -> 4.5.7)
      ```
      ````
