//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreFoundation/CoreFoundation.h>

@class ISStoreClient, NSLock, NSMutableDictionary, Protocol;

@protocol ISAccountService;

@interface ISServiceProxy : NSObject
{
    NSLock *_serviceConnectionLock;
    NSMutableDictionary *_connectionsByServiceName;
    NSMutableDictionary *_localInterfacesByServiceName;
    ISStoreClient *_storeClient;
}

typedef void (^ISErrorHandler)(NSError * __nonnull error);

+ (ISServiceProxy * __nonnull)genericSharedProxy;
@property(retain, nonatomic) ISStoreClient * __nullable storeClient; // @synthesize storeClient=_storeClient;
//- (void)uiServiceSynchronousBlock:(CDUnknownBlockType)arg1;
//@property(readonly, nonatomic) id <ISUIService> uiService;
//- (id)uiServiceWithErrorHandler:(CDUnknownBlockType)arg1;
//- (void)inAppServiceSynchronousBlock:(CDUnknownBlockType)arg1;
//@property(readonly, nonatomic) id <ISInAppService> inAppService;
//- (id)inAppServiceWithErrorHandler:(CDUnknownBlockType)arg1;
//- (void)transactionServiceSynchronousBlock:(CDUnknownBlockType)arg1;
//@property(readonly, nonatomic) id <ISTransactionService> __nullable transactionService;
//- (id __nullable)transactionServiceWithErrorHandler:(ISErrorHandler __nonnull)arg1;
//- (void)assetServiceSynchronousBlock:(CDUnknownBlockType)arg1;
//@property(readonly, nonatomic) id <ISAssetService> assetService;
//- (id)assetServiceWithErrorHandler:(CDUnknownBlockType)arg1;
//- (void)downloadServiceSynchronousBlock:(CDUnknownBlockType)arg1;
//@property(readonly, nonatomic) id <ISDownloadService> downloadService;
//- (id)downloadServiceWithErrorHandler:(CDUnknownBlockType)arg1;
//- (void)accountServiceSynchronousBlock:(void (^ __nonnull)(id <ISAccountService> __nonnull))arg1;
@property(readonly, nonatomic) id <ISAccountService> __nonnull accountService;
//- (id <ISAccountService> __nonnull)accountServiceWithErrorHandler:(ISErrorHandler __nonnull)arg1;
//- (void)performSynchronousBlock:(CDUnknownBlockType)arg1 withServiceName:(id)arg2 protocol:(id)arg3 isMachService:(BOOL)arg4 interfaceClassName:(id)arg5;
//- (id)objectProxyForServiceName:(id)arg1 protocol:(id)arg2 interfaceClassName:(id)arg3 isMachService:(BOOL)arg4 errorHandler:(CDUnknownBlockType)arg5;
//- (id)connectionWithServiceName:(id)arg1 protocol:(id)arg2 isMachService:(BOOL)arg3;
//@property(readonly, nonatomic) Protocol * __nullable exportedProtocol;
//@property(readonly, nonatomic) __weak id <ISServiceRemoteObject> __nullable exportedObject;
- (ISServiceProxy * __nonnull)initWithStoreClient:(ISStoreClient * __nonnull)arg1;

@end

