//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

// #import "NSObject.h"

@class ISStoreClient;


NS_ASSUME_NONNULL_BEGIN

@protocol ISServiceRemoteObject <NSObject>
- (void)startService;
- (void)setStoreClient:(ISStoreClient *)arg1;
@end

NS_ASSUME_NONNULL_END
