//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@protocol ISAccountService <ISServiceRemoteObject>

@required

- (void)accountWithAppleID:(NSString *)appleID replyBlock:(void (^)(ISStoreAccount *))block;
- (void)accountWithDSID:(NSNumber *)dsID replyBlock:(void (^)(ISStoreAccount *))block;
- (void)addAccount:(ISStoreAccount *)account;
- (void)addAccountStoreObserver:(id<ISAccountStoreObserver>)observer;
- (void)addAccountWithAuthenticationResponse:(ISAuthenticationResponse *)authenticationResponse makePrimary:(BOOL)makePrimary replyBlock:(void (^)(ISStoreAccount *))block NS_DEPRECATED_MAC(10_9, 12);
- (void)addURLBagObserver:(id<ISURLBagObserver>)observer;
- (void)authIsExpiredWithReplyBlock:(void (^)(BOOL))block;
- (void)dictionaryForDSID:(NSNumber *)dsID withReplyBlock:(void (^)(NSDictionary *))block NS_AVAILABLE_MAC(13);
- (void)dictionaryWithReplyBlock:(void (^)(NSDictionary *))block;
- (void)generateTouchIDHeadersForDSID:(NSNumber *)dsID challenge:(NSString *)challenge caller:(id)caller replyBlock:(void (^)(NSDictionary *, NSError *))block;
- (void)getTouchIDPreferenceWithReplyBlock:(void (^)(BOOL, ISStoreAccount *, NSError *))block;
- (void)httpHeadersForURL:(NSURL *)url forDSID:(NSNumber *)dsID includeADIHeaders:(BOOL)includeADIHeaders withReplyBlock:(void (^)(NSDictionary *))block;
- (void)iCloudDSIDReplyBlock:(void (^)(NSString *))block;
- (void)invalidateAllBags;
- (void)isValidWithReplyBlock:(void (^)(BOOL))block;
- (void)loadURLBagWithType:(unsigned long long)type replyBlock:(void (^)(BOOL, BOOL, NSError *))block;
- (void)needsSilentADIActionForURL:(NSURL *)url dsID:(NSNumber *)dsID withReplyBlock:(void (^)(BOOL))block NS_AVAILABLE_MAC(13);
- (void)needsSilentADIActionForURL:(NSURL *)url withReplyBlock:(void (^)(BOOL))block;
- (void)parseCreditStringForProtocol:(NSDictionary *)dictionary NS_DEPRECATED_MAC(10_9, 12);
- (void)primaryAccountWithReplyBlock:(void (^)(ISStoreAccount *))block;
- (void)processURLResponse:(NSURLResponse *)urlResponse forRequest:(NSURLRequest *)request;
- (void)processURLResponse:(NSURLResponse *)urlResponse forRequest:(NSURLRequest *)request dsID:(NSNumber *)dsID NS_AVAILABLE_MAC(13);
- (void)recommendedAppleIDForAccountSignIn:(void (^)(NSString *))accountSignIn NS_DEPRECATED_MAC(10_9, 12);
- (void)regexWithKey:(NSString *)key dsID:(NSNumber *)dsID matchesString:(NSString *)string replyBlock:(void (^)(BOOL))block NS_AVAILABLE_MAC(13);
- (void)regexWithKey:(NSString *)key matchesString:(NSString *)string replyBlock:(void (^)(BOOL))block;
- (void)removeAccountStoreObserver:(id<ISAccountStoreObserver>)observer;
- (void)removeURLBagObserver:(id<ISURLBagObserver>)observer;
- (void)retailStoreDemoModeReplyBlock:(void (^)(BOOL, NSString *, NSString *, BOOL))block;
- (void)setStoreFrontID:(NSString *)storefrontID;
- (void)setTouchIDState:(long long)touchIDState forDSID:(NSNumber *)dsID replyBlock:(void (^)(BOOL, NSError *))block;
- (void)shouldSendGUIDWithRequestForURL:(NSURL *)url withReplyBlock:(void (^)(BOOL))block;
- (void)signInWithContext:(ISAuthenticationContext *)context replyBlock:(void (^)(BOOL, ISStoreAccount * _Nullable, NSError * _Nullable))block NS_DEPRECATED_MAC(10_9, 10_12);
- (void)signOut;
- (void)storeFrontWithReplyBlock:(void (^)(NSString *))block;
- (void)updateTouchIDSettingsForDSID:(NSNumber *)dsID replyBlock:(void (^)(BOOL, NSError *))block;
- (void)urlIsTrustedByURLBag:(NSURL *)urlBag dsID:(NSNumber *)dsID withReplyBlock:(void (^)(BOOL))block NS_AVAILABLE_MAC(13);
- (void)urlIsTrustedByURLBag:(NSURL *)urlBag withReplyBlock:(void (^)(BOOL))block;
- (void)valueForURLBagKey:(NSString *)bagKey dsID:(NSNumber *)dsID withReplyBlock:(void (^)(NSURL *))block NS_AVAILABLE_MAC(13);
- (void)valueForURLBagKey:(NSString *)bagKey withReplyBlock:(void (^)(NSURL *))block;

@optional

@end

NS_ASSUME_NONNULL_END
