//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@protocol ISAccountService <ISServiceRemoteObject>

- (void)accountWithAppleID:(NSString *)appleID replyBlock:(void (^)(ISStoreAccount *))block;
- (void)accountWithDSID:(NSNumber *)dsID replyBlock:(void (^)(ISStoreAccount *))block;
- (void)addAccount:(ISStoreAccount *)account;
- (void)addAccountStoreObserver:(id<ISAccountStoreObserver>)observer;
- (void)addAccountWithAuthenticationResponse:(ISAuthenticationResponse *)authenticationResponse makePrimary:(BOOL)makePrimary replyBlock:(void (^)(ISStoreAccount *))block;
- (void)addURLBagObserver:(id<ISURLBagObserver>)observer;
- (void)authIsExpiredWithReplyBlock:(void (^)(BOOL))block;
- (void)dictionaryWithReplyBlock:(void (^)(NSDictionary *))block;
- (void)generateTouchIDHeadersForDSID:(NSNumber *)dsID challenge:(NSString *)challenge caller:(id)caller replyBlock:(void (^)(NSDictionary *, NSError *))block;
- (void)getTouchIDPreferenceWithReplyBlock:(void (^)(BOOL, ISStoreAccount *, NSError *))block;
- (void)httpHeadersForURL:(NSURL *)url forDSID:(NSNumber *)dsID includeADIHeaders:(BOOL)includeADIHeaders withReplyBlock:(void (^)(NSDictionary *))block;
- (void)iCloudDSIDReplyBlock:(void (^)(NSString *))block;
- (void)invalidateAllBags;
- (void)isValidWithReplyBlock:(void (^)(BOOL))block;
- (void)loadURLBagWithType:(unsigned long long)type replyBlock:(void (^)(BOOL, BOOL, NSError *))block;
- (void)needsSilentADIActionForURL:(NSURL *)url withReplyBlock:(void (^)(BOOL))block;
- (void)parseCreditStringForProtocol:(NSDictionary *)dictionary;
- (void)primaryAccountWithReplyBlock:(void (^)(ISStoreAccount *))block;
- (void)processURLResponse:(NSURLResponse *)urlResponse forRequest:(NSURLRequest *)request;
- (void)recommendedAppleIDForAccountSignIn:(void (^)(NSString *))accountSignIn;
- (void)regexWithKey:(NSString *)key matchesString:(NSString *)string replyBlock:(void (^)(BOOL))block;
- (void)removeAccountStoreObserver:(id<ISAccountStoreObserver>)observer;
- (void)removeURLBagObserver:(id<ISURLBagObserver>)observer;
- (void)retailStoreDemoModeReplyBlock:(void (^)(BOOL, NSString *, NSString *, BOOL))block;
- (void)setStoreFrontID:(NSString *)storefrontID;
- (void)setTouchIDState:(long long)touchIDState forDSID:(NSNumber *)dsID replyBlock:(void (^)(BOOL, NSError *))block;
- (void)shouldSendGUIDWithRequestForURL:(NSURL *)url withReplyBlock:(void (^)(BOOL))block;
- (void)signInWithContext:(ISAuthenticationContext *)context replyBlock:(void (^)(BOOL, ISStoreAccount * _Nullable, NSError * _Nullable))block NS_DEPRECATED_MAC(10_9, 10_12);
- (void)signOut;
- (void)storeFrontWithReplyBlock:(void (^)(NSString *))block;
- (void)updateTouchIDSettingsForDSID:(NSNumber *)dsID replyBlock:(void (^)(BOOL, NSError *))block;
- (void)urlIsTrustedByURLBag:(NSURL *)urlBag withReplyBlock:(void (^)(BOOL))block;
- (void)valueForURLBagKey:(NSString *)bagKey withReplyBlock:(void (^)(NSURL *))block;

@end

NS_ASSUME_NONNULL_END
