//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface ISAuthenticationResponse : NSObject <NSSecureCoding> {
	unsigned long long _URLBagType;
	NSString *_accountIdentifier;
	long long _accountKind;
	NSString *_creditString;
	NSNumber *_dsID;
	BOOL _isManagedStudent;
	NSString *_storeFront;
	NSString *_token;
	unsigned long long _urlBagType;
}

+ (BOOL)supportsSecureCoding;

@property unsigned long long URLBagType;
@property(readonly) NSString *accountIdentifier;
@property(readonly) long long accountKind;
@property(readonly) NSString *creditString;
@property(readonly) NSNumber *dsID;
@property(readonly) BOOL isManagedStudent;
@property(readonly) NSString *storeFront;
@property(readonly) NSString *token;

- (BOOL)_loadFromDictionary:(NSDictionary *)dictionary;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (instancetype)initWithDictionary:(NSDictionary *)dictionary;

@end

NS_ASSUME_NONNULL_END
