//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface ISAuthenticationContext : NSObject <NSSecureCoding> {
	long long _style;
}

+ (BOOL)supportsSecureCoding;

@property(readonly) NSNumber *accountID;
@property(retain) NSDictionary *additionalQueryParameters;
@property(retain) NSString *appleIDOverride;
@property(retain) NSString *applicationName;
@property long long authenticationReason;
@property long long authenticationStyle;
@property long long bagType;
@property(retain) NSString *demoAccountName;
@property(retain) NSString *demoAccountPassword;
@property BOOL demoAutologinMode;
@property BOOL demoMode;
@property(retain) NSDictionary *dialogDictionary;
@property BOOL enforceAppleIDOverride;
@property BOOL shouldFollowAccountButtons;
@property(retain) NSDictionary *signUpQueryParameters;
@property BOOL useCachedCredentials;

- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)init;
- (instancetype)initWithAccountID:(NSNumber *)accountID;
- (instancetype)initWithCoder:(NSCoder *)coder;

@end

NS_ASSUME_NONNULL_END
