//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface ISAuthenticationResponse : NSObject <NSSecureCoding> {
	unsigned long long _urlBagType;
}

+ (BOOL)supportsSecureCoding;

@property unsigned long long URLBagType;
@property(readonly) NSString *accountIdentifier;
@property(readonly) long long accountKind;
@property(readonly) NSString *creditString;
@property(readonly) NSNumber *dsID;
@property(readonly) BOOL isManagedStudent;
@property(readonly) NSString *storeFront;
@property(readonly) NSString *token;

- (BOOL)_loadFromDictionary:(NSDictionary *)dictionary;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (instancetype)initWithDictionary:(NSDictionary *)dictionary;

@end

NS_ASSUME_NONNULL_END
