//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface ISAuthenticationContext : NSObject <NSSecureCoding> {
	NSNumber *_accountID;
	NSDictionary *_additionalQueryParameters;
	NSString *_appleIDOverride;
	NSString *_applicationName;
	long long _authenticationReason;
	long long _bagType;
	NSString *_demoAccountName;
	NSString *_demoAccountPassword;
	BOOL _demoAutologinMode;
	BOOL _demoMode;
	NSDictionary *_dialogDictionary;
	BOOL _enforceAppleIDOverride;
	BOOL _shouldFollowAccountButtons;
	NSDictionary *_signUpQueryParameters;
	long long _style;
	BOOL _useCachedCredentials;
}

+ (BOOL)supportsSecureCoding;

@property(readonly) NSNumber *accountID; // @synthesize accountID=_accountID;
@property(retain) NSDictionary *additionalQueryParameters; // @synthesize additionalQueryParameters=_additionalQueryParameters;
@property(retain) NSString *appleIDOverride; // @synthesize appleIDOverride=_appleIDOverride;
@property(retain) NSString *applicationName; // @synthesize applicationName=_applicationName;
@property long long authenticationReason; // @synthesize authenticationReason=_authenticationReason;
@property long long authenticationStyle; // @synthesize authenticationStyle=_style;
@property long long bagType; // @synthesize bagType=_bagType;
@property(retain) NSString *demoAccountName; // @synthesize demoAccountName=_demoAccountName;
@property(retain) NSString *demoAccountPassword; // @synthesize demoAccountPassword=_demoAccountPassword;
@property BOOL demoAutologinMode; // @synthesize demoAutologinMode=_demoAutologinMode;
@property BOOL demoMode; // @synthesize demoMode=_demoMode;
@property(retain) NSDictionary *dialogDictionary; // @synthesize dialogDictionary=_dialogDictionary;
@property BOOL enforceAppleIDOverride; // @synthesize enforceAppleIDOverride=_enforceAppleIDOverride;
@property BOOL shouldFollowAccountButtons; // @synthesize shouldFollowAccountButtons=_shouldFollowAccountButtons;
@property(retain) NSDictionary *signUpQueryParameters; // @synthesize signUpQueryParameters=_signUpQueryParameters;
@property BOOL useCachedCredentials; // @synthesize useCachedCredentials=_useCachedCredentials;

- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)init;
- (instancetype)initWithAccountID:(NSNumber *)accountID;
- (instancetype)initWithCoder:(NSCoder *)coder;

//- (void).cxx_destruct;

@end

NS_ASSUME_NONNULL_END
