//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface ISServiceProxy : NSObject {
	ISStoreClient *_storeClient;
}

+ (instancetype)genericSharedProxy;
+ (void)initialize;

@property(readonly, nonatomic) id<ISAccountService> accountService;
@property(readonly, nonatomic) id<ISAssetService> assetService;
@property(readonly, nonatomic) id<ISDownloadService> downloadService;
@property(readonly, nonatomic, weak) id<ISServiceRemoteObject> exportedObject;
@property(readonly, nonatomic) Protocol *exportedProtocol;
@property(readonly, nonatomic) id<ISInAppService> inAppService;
@property(retain, nonatomic, nullable) ISStoreClient *storeClient;
@property(readonly, nonatomic) id<ISTransactionService> transactionService;
@property(readonly, nonatomic) id<ISUIService> uiService;

- (void)accountServiceSynchronousBlock:(UnknownBlock *)block;
- (id<ISAccountService>)accountServiceWithErrorHandler:(UnknownBlock *)handler;
- (void)assetServiceSynchronousBlock:(UnknownBlock *)block;
- (id<ISAssetService>)assetServiceWithErrorHandler:(UnknownBlock *)handler;
- (void)connectionWasInterrupted;
- (id)connectionWithServiceName:(NSString *)serviceName protocol:(id)protocol isMachService:(BOOL)isMachService;
- (void)downloadServiceSynchronousBlock:(UnknownBlock *)block;
- (id<ISDownloadService>)downloadServiceWithErrorHandler:(UnknownBlock *)handler;
- (void)inAppServiceSynchronousBlock:(UnknownBlock *)block;
- (id<ISInAppService>)inAppServiceWithErrorHandler:(UnknownBlock *)handler;
- (instancetype)initWithStoreClient:(ISStoreClient *)client;
- (id)objectProxyForServiceName:(NSString *)serviceName protocol:(id)protocol interfaceClassName:(NSString *)interfaceClassName isMachService:(BOOL)isMachService errorHandler:(UnknownBlock *)handler;
- (void)performSynchronousBlock:(UnknownBlock *)block withServiceName:(NSString *)serviceName protocol:(id)protocol isMachService:(BOOL)isMachService interfaceClassName:(NSString *)interfaceClassName;
- (void)registerForInterrptionNotification;
- (void)transactionServiceSynchronousBlock:(UnknownBlock *)block;
- (id<ISTransactionService>)transactionServiceWithErrorHandler:(UnknownBlock *)handler;
- (void)uiServiceSynchronousBlock:(UnknownBlock *)block;
- (id<ISUIService>)uiServiceWithErrorHandler:(UnknownBlock *)handler;

@end

NS_ASSUME_NONNULL_END
