//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface ISServiceProxy : NSObject {
	ISStoreClient *_storeClient;
}

+ (ISServiceProxy * __nonnull)genericSharedProxy;
+ (void)initialize;

@property(readonly, nonatomic) id<ISAccountService> accountService;
@property(readonly, nonatomic) id<ISAssetService> assetService;
@property(readonly, nonatomic) id<ISDownloadService> downloadService;
@property(readonly, nonatomic, weak) id<ISServiceRemoteObject> exportedObject;
@property(readonly, nonatomic) Protocol *exportedProtocol;
@property(readonly, nonatomic) id<ISInAppService> inAppService;
@property(retain, nonatomic, nullable) ISStoreClient *storeClient; // @synthesize storeClient=_storeClient;
@property(readonly, nonatomic) id<ISTransactionService> transactionService;
@property(readonly, nonatomic) id<ISUIService> uiService;

- (void)accountServiceSynchronousBlock:(UnknownBlock *)arg1;
- (id)accountServiceWithErrorHandler:(UnknownBlock *)arg1;
- (void)assetServiceSynchronousBlock:(UnknownBlock *)arg1;
- (id)assetServiceWithErrorHandler:(UnknownBlock *)arg1;
- (void)connectionWasInterrupted;
- (id)connectionWithServiceName:(id)arg1 protocol:(id)arg2 isMachService:(BOOL)arg3;
- (void)downloadServiceSynchronousBlock:(UnknownBlock *)arg1;
- (id)downloadServiceWithErrorHandler:(UnknownBlock *)arg1;
- (void)inAppServiceSynchronousBlock:(UnknownBlock *)arg1;
- (id)inAppServiceWithErrorHandler:(UnknownBlock *)arg1;
- (ISServiceProxy * __nonnull)initWithStoreClient:(ISStoreClient * __nonnull)arg1;
- (id)objectProxyForServiceName:(id)arg1 protocol:(id)arg2 interfaceClassName:(id)arg3 isMachService:(BOOL)arg4 errorHandler:(UnknownBlock *)arg5;
- (void)performSynchronousBlock:(UnknownBlock *)arg1 withServiceName:(id)arg2 protocol:(id)arg3 isMachService:(BOOL)arg4 interfaceClassName:(id)arg5;
- (void)registerForInterrptionNotification;
- (void)transactionServiceSynchronousBlock:(UnknownBlock *)arg1;
- (id)transactionServiceWithErrorHandler:(UnknownBlock *)arg1;
- (void)uiServiceSynchronousBlock:(UnknownBlock *)arg1;
- (id)uiServiceWithErrorHandler:(UnknownBlock *)arg1;

//- (void).cxx_destruct;

@end

NS_ASSUME_NONNULL_END
