//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@protocol ISServiceRemoteObject <NSObject>

- (void)setStoreClient:(ISStoreClient *)client;
- (void)startService;

@end

NS_ASSUME_NONNULL_END
