//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@protocol ISServiceRemoteObject <NSObject>

@required

- (void)setStoreClient:(ISStoreClient *)client;
- (void)startService;

@optional

@end

NS_ASSUME_NONNULL_END
