//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface ISStoreClient : NSObject <NSSecureCoding> {
	BOOL __alwaysUseSandboxEnvironment;
	NSString *_agentListenerName;
	NSString *_agentPreferencesDomain;
	NSString *_appPath;
	NSString *_appPreferencesDomain;
	NSString *_aslDomain;
	long long _clientType;
	NSDictionary *_daap;
	NSString *_displayUIHostID;
	unsigned long long _frameworkVersion;
	NSString *_identifier;
	BOOL _isDaemon;
	long long _mediaTypeMask;
	int _pid;
	ISStoreAccount *_primaryAccount;
	NSArray *_productionBagURLs;
	NSString *_pushServiceName;
	long long _requiredBagType;
	NSArray *_sandboxBagURLs;
	NSString *_storeFrontBagKey;
	NSString *_storeSecureURLScheme;
	NSString *_storeURLScheme;
	NSString *_tempPathClientIdentifier;
	NSString *_toolbarBagKey;
	NSString *_userAgentAppName;
	NSString *_userAgentAppVersion;
}

+ (instancetype)knownClientWithIdentifier:(NSString *)identifier frameworkVersion:(unsigned long long)frameworkVersion;
+ (BOOL)supportsSecureCoding;

@property(setter=_setAlwaysUseSandboxEnvironment:) BOOL _alwaysUseSandboxEnvironment;
@property(copy) NSString *agentListenerName;
@property(copy) NSString *agentPreferencesDomain;
@property(copy) NSString *appPath;
@property(copy) NSString *appPreferencesDomain;
@property(copy) NSString *aslDomain;
@property long long clientType;
@property(copy) NSDictionary *daap;
@property(copy) NSString *displayUIHostID;
@property unsigned long long frameworkVersion;
@property(copy) NSString *identifier;
@property BOOL isDaemon;
@property long long mediaTypeMask;
@property(readonly) int pid;
@property(copy) ISStoreAccount *primaryAccount;
@property(copy) NSArray *productionBagURLs;
@property(copy) NSString *pushServiceName;
@property long long requiredBagType;
@property(copy) NSArray *sandboxBagURLs;
@property(copy) NSString *storeFrontBagKey;
@property(copy) NSString *storeSecureURLScheme;
@property(copy) NSString *storeURLScheme;
@property(copy) NSString *tempPathClientIdentifier;
@property(copy) NSString *toolbarBagKey;
@property(copy) NSString *userAgentAppName;
@property(copy) NSString *userAgentAppVersion;

- (void)_cacheKnownClient:(ISStoreClient *)client;
- (id)callerIdentity;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)init;
- (instancetype)initWithApplicationPath:(NSString *)path;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (instancetype)initWithStoreClientType:(long long)type;
- (BOOL)isEqualToStoreClient:(ISStoreClient *)client;

@end

NS_ASSUME_NONNULL_END
