//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface ISStoreClient : NSObject <NSSecureCoding>

+ (instancetype)knownClientWithIdentifier:(NSString *)identifier frameworkVersion:(unsigned long long)frameworkVersion;
+ (BOOL)supportsSecureCoding;

@property(setter=_setAlwaysUseSandboxEnvironment:) BOOL _alwaysUseSandboxEnvironment;
@property(copy) NSString *agentListenerName;
@property(copy) NSString *agentPreferencesDomain;
@property(copy) NSString *appPath;
@property(copy) NSString *appPreferencesDomain;
@property(copy) NSString *aslDomain;
@property long long clientType;
@property(copy) NSDictionary *daap;
@property(copy) NSString *displayUIHostID;
@property unsigned long long frameworkVersion;
@property(copy) NSString *identifier;
@property BOOL isDaemon;
@property(readonly) NSString *mediaType NS_AVAILABLE_MAC(13);
@property long long mediaTypeMask;
@property(readonly) int pid;
@property(copy) ISStoreAccount *primaryAccount;
@property(copy) NSArray *productionBagURLs;
@property(copy) NSString *pushServiceName;
@property long long requiredBagType;
@property(copy) NSArray *sandboxBagURLs;
@property(copy) NSString *storeFrontBagKey;
@property(copy) NSString *storeSecureURLScheme;
@property(copy) NSString *storeURLScheme;
@property(copy) NSString *tempPathClientIdentifier;
@property(copy) NSString *toolbarBagKey;
@property(copy) NSString *userAgentAppName;
@property(copy) NSString *userAgentAppVersion;

- (void)_cacheKnownClient:(ISStoreClient *)client;
- (id)callerIdentity;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)init;
- (instancetype)initWithApplicationPath:(NSString *)path;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (instancetype)initWithStoreClientType:(long long)type;
- (BOOL)isEqualToStoreClient:(ISStoreClient *)client;

@end

NS_ASSUME_NONNULL_END
