//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface ISStoreAccount : NSObject <NSSecureCoding> {
	long long _URLBagType;
	NSString *_creditString;
	NSNumber *_dsID;
	NSString *_identifier;
	BOOL _isManagedStudent;
	BOOL _isSignedIn;
	long long _kind;
	NSString *_password;
	BOOL _primary;
	NSString *_storeFront;
	NSString *_token;
	NSTimer *_tokenExpirationTimer;
	NSTimer *_tokenInvalidTimer;
	NSDate *_tokenIssuedDate;
	long long _touchIDState;
}

+ (id)dsidFromPlistValue:(id)arg1;
+ (id)migratePersistedStoreDictionary:(id)arg1;
+ (BOOL)supportsSecureCoding;

@property long long URLBagType; // @synthesize URLBagType=_URLBagType;
@property(readonly, getter=isAuthenticated) BOOL authenticated;
@property(copy) NSString *creditString; // @synthesize creditString=_creditString;
@property(copy) NSNumber *dsID; // @synthesize dsID=_dsID;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
@property BOOL isManagedStudent; // @synthesize isManagedStudent=_isManagedStudent;
@property BOOL isSignedIn; // @synthesize isSignedIn=_isSignedIn;
@property long long kind; // @synthesize kind=_kind;
@property(copy) NSString *password; // @synthesize password=_password;
@property(readonly, getter=isPrimary) BOOL primary; // @synthesize primary=_primary;
@property(retain) NSString *storeFront; // @synthesize storeFront=_storeFront;
@property(copy) NSString *token; // @synthesize token=_token;
@property(retain) NSTimer *tokenExpirationTimer; // @synthesize tokenExpirationTimer=_tokenExpirationTimer;
@property(retain) NSDate *tokenIssuedDate; // @synthesize tokenIssuedDate=_tokenIssuedDate;
@property long long touchIDState; // @synthesize touchIDState=_touchIDState;

- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (long long)getTouchIDState;
- (BOOL)hasValidStrongToken;
- (id)initWithCoder:(id)arg1;
- (id)initWithPersistedStoreDictionary:(id)arg1;
- (void)mergeValuesFromAuthenticationResponse:(id)arg1;
- (id)persistedStoreDictionary;
- (void)resetTouchIDState;
- (double)strongTokenValidForSecond;

//- (void).cxx_destruct;

@end

NS_ASSUME_NONNULL_END
