//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface ISStoreAccount : NSObject <NSSecureCoding> {
	long long _URLBagType;
	NSString *_creditString;
	NSNumber *_dsID;
	NSString *_identifier;
	BOOL _isManagedStudent;
	BOOL _isSignedIn;
	long long _kind;
	NSString *_password;
	BOOL _primary;
	NSString *_storeFront;
	NSString *_token;
	NSTimer *_tokenExpirationTimer;
	NSTimer *_tokenInvalidTimer;
	NSDate *_tokenIssuedDate;
	long long _touchIDState;
}

+ (NSNumber *)dsidFromPlistValue:(id)value;
+ (NSDictionary *)migratePersistedStoreDictionary:(NSDictionary *)dictionary;
+ (BOOL)supportsSecureCoding;

@property long long URLBagType;
@property(readonly, getter=isAuthenticated) BOOL authenticated;
@property(copy) NSString *creditString;
@property(copy) NSNumber *dsID;
@property(copy) NSString *identifier;
@property BOOL isManagedStudent;
@property BOOL isSignedIn;
@property long long kind;
@property(copy) NSString *password;
@property(readonly, getter=isPrimary) BOOL primary;
@property(retain) NSString *storeFront;
@property(copy) NSString *token;
@property(retain) NSTimer *tokenExpirationTimer;
@property(retain) NSDate *tokenIssuedDate;
@property long long touchIDState;

- (NSString *)description;
- (void)encodeWithCoder:(NSCoder *)coder;
- (long long)getTouchIDState;
- (BOOL)hasValidStrongToken;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (instancetype)initWithPersistedStoreDictionary:(NSDictionary *)dictionary;
- (void)mergeValuesFromAuthenticationResponse:(ISAuthenticationResponse *)response;
- (NSDictionary *)persistedStoreDictionary;
- (void)resetTouchIDState;
- (double)strongTokenValidForSecond;

@end

NS_ASSUME_NONNULL_END
