//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface SSDownloadPhase : NSObject <NSSecureCoding, NSCopying> {
	SSOperationProgress *_operationProgress;
}

+ (BOOL)supportsSecureCoding;

@property(readonly) double estimatedSecondsRemaining;
@property(readonly) SSOperationProgress *operationProgress;
@property(readonly) long long phaseType;
@property(readonly) float progressChangeRate;
@property(readonly) long long progressUnits;
@property(readonly) long long progressValue;
@property(readonly) long long totalProgressValue;

- (id)copyWithZone:(nullable struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithOperationProgress:(id)arg1;

//- (void).cxx_destruct;

@end

NS_ASSUME_NONNULL_END
