//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.626, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.3)
// - LC_SOURCE_VERSION: 716.0.8.0.0
//

@interface SSDownload : NSObject <NSSecureCoding> {
	BOOL _needsPreInstallValidation;
}

+ (BOOL)supportsSecureCoding;

@property (copy, nullable) NSNumber *accountDSID;
@property (copy, nonatomic, nullable) NSArray<SSDownloadAsset *> *assets; // Unverified generic type
@property (copy, nullable) NSString *cancelURLString;
@property (copy, nullable) NSString *customDownloadPath;
@property BOOL didAutoUpdate;
@property unsigned long long downloadType;
@property BOOL installAfterLogout;
@property (copy, nullable) NSString *installPath;
@property BOOL isInServerQueue;
@property (copy, nonatomic, nullable) SSDownloadMetadata *metadata;
@property BOOL needsDisplayInDock;
@property (copy, nullable) NSURL *relaunchAppWithBundleURL;
@property BOOL skipAssetDownloadIfNotAlreadyOnDisk;
@property BOOL skipInstallPhase;
@property (retain, nonatomic, nullable) SSDownloadStatus *status;

- (void)cancel;
- (void)cancelWithPrompt:(BOOL)prompt;
- (void)cancelWithPrompt:(BOOL)prompt storeClient:(nullable ISStoreClient *)client;
- (void)cancelWithStoreClient:(nullable ISStoreClient *)client;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithAssets:(nullable NSArray<SSDownloadAsset *> *)assets metadata:(nullable SSDownloadMetadata *)metadata; // Unverified assets type / metadata type
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (void)pause;
- (void)pauseWithStoreClient:(nullable ISStoreClient *)client;
- (nullable SSDownloadAsset *)primaryAsset;
- (void)resume;
- (void)resumeWithStoreClient:(nullable ISStoreClient *)client;
- (void)setUseUniqueDownloadFolder:(BOOL)useUniqueDownloadFolder;

@end
