//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface SSDownloadPhase : NSObject <NSSecureCoding, NSCopying>

+ (BOOL)supportsSecureCoding;

@property(readonly) double estimatedSecondsRemaining;
@property(readonly) SSOperationProgress *operationProgress;
@property(readonly) long long phaseType;
@property(readonly) float progressChangeRate;
@property(readonly) long long progressUnits;
@property(readonly) long long progressValue;
@property(readonly) long long totalProgressValue;

- (instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)init;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (instancetype)initWithOperationProgress:(SSOperationProgress *)progress;

@end

NS_ASSUME_NONNULL_END
