//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.626, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.3)
// - LC_SOURCE_VERSION: 716.0.8.0.0
//

@interface SSDownloadPhase : NSObject <NSSecureCoding, NSCopying>

+ (BOOL)supportsSecureCoding;

@property (readonly) double estimatedSecondsRemaining;
@property (readonly, nullable) SSOperationProgress *operationProgress;
@property (readonly) long long phaseType;
@property (readonly) float progressChangeRate;
@property (readonly) long long progressUnits;
@property (readonly) long long progressValue;
@property (readonly) long long totalProgressValue;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder; // Unverified coder type
- (nonnull instancetype)initWithOperationProgress:(nullable SSOperationProgress *)progress; // Unverified progress type

@end
