//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

@interface SSDownloadStatus : NSObject <NSSecureCoding>

+ (BOOL)supportsSecureCoding;

@property(readonly, nonatomic, nullable) SSDownloadPhase *activePhase;
@property(nonatomic, getter=isCancelled) BOOL cancelled;
@property(retain, nonatomic, nullable) NSError *error;
@property(nonatomic, getter=isFailed) BOOL failed;
@property(readonly, nonatomic, getter=isPausable) BOOL pausable;
@property(nonatomic, getter=isPaused) BOOL paused;
@property(readonly, nonatomic) float percentComplete;
@property(readonly, nonatomic) float phasePercentComplete;
@property(readonly, nonatomic) long long phaseTimeRemaining;
@property BOOL waiting;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (void)setOperationProgress:(nullable SSOperationProgress *)progress; // Unverified progress type

@end
