//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface SSDownload : NSObject <NSSecureCoding> {
	NSNumber *_accountDSID;
	NSArray<ISAsset *> *_assets;
	NSString *_cancelURLString;
	BOOL _didAutoUpdate;
	unsigned long long _downloadType;
	BOOL _installAfterLogout;
	NSString *_installPath;
	BOOL _isInServerQueue;
	SSDownloadMetadata *_metadata;
	BOOL _needsDisplayInDock;
	BOOL _needsPreInstallValidation;
	NSURL *_relaunchAppWithBundleURL;
	BOOL _skipAssetDownloadIfNotAlreadyOnDisk;
	SSDownloadStatus *_status;
}

+ (BOOL)supportsSecureCoding;

@property(copy) NSNumber *accountDSID;
@property(copy, nonatomic) NSArray<ISAsset *> *assets;
@property(copy) NSString *cancelURLString;
@property(copy) NSString *customDownloadPath;
@property BOOL didAutoUpdate;
@property unsigned long long downloadType;
@property BOOL installAfterLogout;
@property(copy) NSString *installPath;
@property BOOL isInServerQueue;
@property(copy, nonatomic) SSDownloadMetadata *metadata;
@property BOOL needsDisplayInDock;
@property(copy) NSURL *relaunchAppWithBundleURL;
@property BOOL skipAssetDownloadIfNotAlreadyOnDisk;
@property BOOL skipInstallPhase;
@property(retain, nonatomic) SSDownloadStatus *status;

- (void)cancel;
- (void)cancelWithPrompt:(BOOL)prompt;
- (void)cancelWithPrompt:(BOOL)prompt storeClient:(ISStoreClient *)client;
- (void)cancelWithStoreClient:(ISStoreClient *)client;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)init;
- (instancetype)initWithAssets:(NSArray<ISAsset *> *)assets metadata:(SSDownloadMetadata *)metadata;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (BOOL)isEqual:(nullable id)object;
- (void)pause;
- (void)pauseWithStoreClient:(ISStoreClient *)client;
- (ISAsset *)primaryAsset;
- (void)resume;
- (void)resumeWithStoreClient:(ISStoreClient *)client;
- (void)setUseUniqueDownloadFolder:(BOOL)useUniqueDownloadFolder;

@end

NS_ASSUME_NONNULL_END
