//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.626, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.3)
// - LC_SOURCE_VERSION: 716.0.8.0.0
//

@interface SSDownloadStatus : NSObject <NSSecureCoding>

+ (BOOL)supportsSecureCoding;

@property (readonly, nonatomic, nullable) SSDownloadPhase *activePhase;
@property (nonatomic, getter=isCancelled) BOOL cancelled;
@property (retain, nonatomic, nullable) NSError *error;
@property (nonatomic, getter=isFailed) BOOL failed;
@property (readonly, nonatomic, getter=isPausable) BOOL pausable;
@property (nonatomic, getter=isPaused) BOOL paused;
@property (readonly, nonatomic) float percentComplete;
@property (readonly, nonatomic) float phasePercentComplete;
@property (readonly, nonatomic) long long phaseTimeRemaining;
@property BOOL waiting;

- (nonnull instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (void)setOperationProgress:(nullable SSOperationProgress *)progress; // Unverified progress type

@end
