//
// Generated by class-dump 3.5 (64 bit).
//
// class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

NS_ASSUME_NONNULL_BEGIN

@interface SSPurchaseResponse : NSObject <NSSecureCoding> {
	NSArray *_downloads;
	NSDictionary *_metrics;
	NSDictionary *_rawResponse;
}

+ (BOOL)supportsSecureCoding;

@property(retain) NSArray<SSDownload*> *downloads; // @synthesize downloads=_downloads;
@property(retain) NSDictionary *metrics; // @synthesize metrics=_metrics;

- (id)_newDownloadsFromItems:(id)arg1 withDSID:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1 userIdentifier:(id)arg2;

//- (void).cxx_destruct;

@end

NS_ASSUME_NONNULL_END
