//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface SSPurchase : NSObject <NSSecureCoding, NSCopying> {
	NSNumber *_accountIdentifier;
	NSString *_appleID;
	UnknownBlock *_authFallbackHandler;
	NSString *_buyParameters;
	BOOL _checkPreflightAterPurchase;
	SSDownloadMetadata *_downloadMetadata;
	NSDictionary *_dsidLessOptions;
	BOOL _isCancelled;
	BOOL _isDSIDLessPurchase;
	BOOL _isRedownload;
	BOOL _isUpdate;
	BOOL _isVPP;
	unsigned long long _itemIdentifier;
	NSString *_parentalControls;
	ISOperation *_purchaseOperation;
	long long _purchaseType;
	NSData *_receiptData;
	NSDictionary *_responseDialog;
	BOOL _shouldBeInstalledAfterLogout;
	NSString *_sortableAccountIdentifier;
	NSString *_uniqueIdentifier;
}

+ (instancetype)purchaseWithBuyParameters:(NSString *)buyParameters;
+ (NSDictionary<NSNumber *, SSPurchase *> *)purchasesGroupedByAccountIdentifierWithPurchases:(NSArray<SSPurchase *> *)purchases;
+ (BOOL)supportsSecureCoding;

@property(retain, nonatomic) NSNumber *accountIdentifier;
@property(retain, nonatomic) NSString *appleID;
@property(copy) UnknownBlock *authFallbackHandler;
@property(copy, nonatomic) NSString *buyParameters;
@property BOOL checkPreflightAterPurchase;
@property(copy, nonatomic) SSDownloadMetadata *downloadMetadata;
@property(retain) NSDictionary *dsidLessOptions;
@property BOOL isCancelled;
@property BOOL isDSIDLessPurchase;
@property BOOL isRecoveryPurchase;
@property BOOL isRedownload;
@property BOOL isUpdate;
@property BOOL isVPP;
@property unsigned long long itemIdentifier;
@property(retain, nonatomic) NSString *managedAppUUIDString NS_AVAILABLE_MAC(13);
@property(readonly) BOOL needsAuthentication;
@property(retain, nonatomic) NSString *parentalControls;
@property(weak) ISOperation *purchaseOperation;
@property(nonatomic) long long purchaseType;
@property(retain, nonatomic) NSData *receiptData;
@property(copy) NSDictionary *responseDialog;
@property BOOL shouldBeInstalledAfterLogout;
@property(readonly, nonatomic) NSString *sortableAccountIdentifier;
@property(readonly, nonatomic) NSString *uniqueIdentifier;

- (NSString *)_sortableAccountIdentifier;
- (instancetype)copyWithZone:(nullable struct _NSZone *)zone;
- (NSString *)description;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (NSNumber *)productID;
- (BOOL)purchaseDSIDMatchesPrimaryAccount;

@end

NS_ASSUME_NONNULL_END
