//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.626, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.3)
// - LC_SOURCE_VERSION: 716.0.8.0.0
//

@interface SSPurchaseResponse : NSObject <NSSecureCoding> {
	NSDictionary *_rawResponse;
}

+ (BOOL)supportsSecureCoding;

@property (retain, nullable) NSArray<SSDownload *> *downloads;
@property (retain, nullable) NSDictionary<NSString *, id> *metrics;

- (nonnull NSMutableArray<SSDownload *> *)_newDownloadsFromItems:(nullable NSArray<NSDictionary *> *)items withDSID:(nullable NSNumber *)dsID; // Unverified items element generic types / dsID type
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithDictionary:(nullable NSDictionary *)dictionary userIdentifier:(nullable NSString *)userIdentifier; // Unverified dictionary generic types / userIdentifier type

@end
