//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.603, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.5, SDK: 15.5, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

NS_ASSUME_NONNULL_BEGIN

@interface SSPurchaseResponse : NSObject <NSSecureCoding> {
	NSArray<SSDownload *> *_downloads;
	NSDictionary *_metrics;
	NSDictionary *_rawResponse;
}

+ (BOOL)supportsSecureCoding;

@property(retain) NSArray<SSDownload *> *downloads;
@property(retain) NSDictionary *metrics;

- (NSArray<SSDownload *> *)_newDownloadsFromItems:(NSArray *)items withDSID:(NSNumber *)dsID;
- (void)encodeWithCoder:(NSCoder *)coder;
- (instancetype)initWithCoder:(NSCoder *)coder;
- (instancetype)initWithDictionary:(NSDictionary *)dictionary userIdentifier:(NSString *)userIdentifier;

@end

NS_ASSUME_NONNULL_END
