//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.624, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.6, SDK: 15.6, Tool: ld (1167.3)
// - LC_SOURCE_VERSION: 715.5.1.0.0
//

@import Foundation;

@class ISAuthenticationContext, ISAuthenticationResponse, ISOperation, ISStoreClient, SSDownloadAsset, SSOperationProgress;

@protocol ISAccountStoreObserver, ISAssetService, ISDownloadService, ISInAppService, ISServiceRemoteObject, ISTransactionService, ISUIService, ISURLBagObserver;

typedef void (^UnknownBlock)();

#import <ISStoreAccount.h>
#import <ISAccountService-Protocol.h>
#import <ISServiceProxy.h>
#import <SSDownloadMetadata.h>
#import <SSDownloadPhase.h>
#import <SSDownloadStatus.h>
#import <SSDownload.h>
#import <SSPurchase.h>
#import <SSPurchaseResponse.h>
