//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.626, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26, SDK: 26, Tool: ld (1220.3)
// - LC_SOURCE_VERSION: 716.0.8.0.0
//

@import Foundation;

@class ISAuthenticationContext, ISAuthenticationResponse, ISOperation, ISStoreClient, SSDownloadAsset, SSOperationProgress;

@protocol ISAccountStoreObserver, ISAssetService, ISDownloadService, ISInAppService, ISServiceRemoteObject, ISTransactionService, ISUIService, ISURLBagObserver;

typedef void (^UnknownBlock)();

#import "ISStoreAccount.h"
#import "ISAccountService-Protocol.h"
#import "ISServiceProxy.h"
#import "SSDownloadMetadata.h"
#import "SSDownloadPhase.h"
#import "SSDownloadStatus.h"
#import "SSDownload.h"
#import "SSPurchase.h"
#import "SSPurchaseResponse.h"
