//
// Generated by https://github.com/blacktop/ipsw (Version: 3.1.647, BuildCommit: Homebrew)
//
// - LC_BUILD_VERSION:  Platform: macOS, MinOS: 26.2, SDK: 26.2, Tool: ld (1230.3)
// - LC_SOURCE_VERSION: 716.2.2.0.0
//

@interface ISStoreAccount : NSObject <NSSecureCoding> {
	NSTimer *_tokenInvalidTimer;
}

+ (nullable NSNumber *)dsidFromPlistValue:(nullable id)value;
+ (nonnull NSDictionary *)migratePersistedStoreDictionary:(nullable NSDictionary *)dictionary;
+ (BOOL)supportsSecureCoding;

@property long long URLBagType;
@property (readonly, getter=isAuthenticated) BOOL authenticated;
@property (copy, nullable) NSString *creditString;
@property (copy, nullable) NSNumber *dsID;
@property (copy, nullable) NSString *identifier;
@property BOOL isManagedStudent;
@property BOOL isSignedIn;
@property long long kind;
@property (copy, nullable) NSString *password;
@property (readonly, getter=isPrimary) BOOL primary;
@property (retain, nullable) NSString *storeFront;
@property (copy, nullable) NSString *token;
@property (retain, nullable) NSTimer *tokenExpirationTimer;
@property (retain, nullable) NSDate *tokenIssuedDate;
@property long long touchIDState;

- (nonnull NSString *)description;
- (void)encodeWithCoder:(nullable NSCoder *)coder;
- (long long)getTouchIDState;
- (BOOL)hasValidStrongToken;
- (nonnull instancetype)initWithCoder:(nullable NSCoder *)coder;
- (nonnull instancetype)initWithPersistedStoreDictionary:(nullable NSDictionary *)dictionary;
- (void)mergeValuesFromAuthenticationResponse:(nullable ISAuthenticationResponse *)response;
- (nonnull NSDictionary<NSString *, NSNumber *> *)persistedStoreDictionary;
- (void)resetTouchIDState;
- (double)strongTokenValidForSecond;

@end
