//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISServiceRemoteObject.h"

@class CKSoftwareProduct, NSArray, NSDictionary, NSNumber, NSString, NSURL, SSDownload;

@protocol ISAssetService <ISServiceRemoteObject>
- (void)didClickOnWhatsNewMenuItem;
- (void)purchasedItemsWithReplyBlock:(void (^)(NSArray *))arg1;
- (void)pollForPurchasedItems:(BOOL)arg1;
- (void)redownloadBooksWithItemIdentifiers:(NSArray *)arg1 dsid:(NSNumber *)arg2;
- (void)pollForPurchasedBooksWithReplyBlock:(void (^)(BOOL))arg1;
- (void)removeLibraryObserver:(id <ISBookLibraryObserver>)arg1;
- (void)addLibraryObserver:(id <ISBookLibraryObserver>)arg1;
- (void)hasSampleWithItemIdentifier:(NSNumber *)arg1 replyBlock:(void (^)(BOOL, NSDictionary *))arg2;
- (void)bookWithInfo:(NSDictionary *)arg1 replyBlock:(void (^)(CKBook *))arg2;
- (void)bookAtIndexWithInfo:(NSDictionary *)arg1 replyBlock:(void (^)(CKBook *))arg2;
- (void)sortedBooksWithInfo:(NSDictionary *)arg1 replyBlock:(void (^)(NSArray *))arg2;
- (void)countOfBooksWithInfo:(NSDictionary *)arg1 replyBlock:(void (^)(unsigned long long))arg2;
- (void)softwareUpdateDidFinishBackgroundScanWithInfo:(NSDictionary *)arg1;
- (void)adaptableBundleIdentifiersWithReplyBlock:(void (^)(NSArray *))arg1;
- (void)adoptionCompletedForBundleIDWithInfo:(NSDictionary *)arg1 replyBlock:(void (^)(NSDictionary *))arg2;
- (void)adoptionEligibilityResponseWithReplyBlock:(void (^)(NSDictionary *))arg1;
- (void)adoptBundleIDsWithInfo:(NSDictionary *)arg1 replyBlock:(void (^)(BOOL, NSDictionary *, NSError *))arg2;
- (void)startAdoptionEligibilityCheckWithReplyBlock:(void (^)(BOOL, NSDictionary *))arg1;
- (void)processMDMManifestURL:(NSURL *)arg1 options:(NSDictionary *)arg2 storeClientType:(long long)arg3 replyBlock:(void (^)(BOOL, NSArray *, NSError *))arg4;
- (void)redownloadWithItemIdentifier:(long long)arg1 bundleIdentifier:(NSString *)arg2 storeClientType:(long long)arg3 replyBlock:(void (^)(BOOL, long long, NSString *, NSError *))arg4;
- (void)showInvite:(NSURL *)arg1 organizationName:(NSString *)arg2 storeClientType:(long long)arg3;
- (void)laterDidNotOccurWithDueToACPower:(BOOL)arg1;
- (void)nowIsLaterWithMode:(long long)arg1 countdownDeferred:(BOOL)arg2;
- (void)updateAutoInfoWithToken:(NSString *)arg1 replyBlock:(void (^)(NSDictionary *))arg2;
- (void)promptUserToOptInForAutoUpdateWithShowNotification:(BOOL)arg1;
- (void)shouldPromptForAutoUpdateOptInWithReplyBlock:(void (^)(BOOL))arg1;
- (void)isAutoUpdateEnabledWithReplyBlock:(void (^)(BOOL))arg1;
- (void)installedUpdatesJournalWithReplyBlock:(void (^)(NSArray *))arg1;
- (void)cancelUpdatesToBeInstalledLater;
- (void)appUpdatesToInstallLaterWithReplyBlock:(void (^)(NSArray *))arg1;
- (void)installAvailableUpdatesLaterWithMode:(long long)arg1;
- (void)shouldOfferDoItLaterForAvailableUpdatesWithReplyBlock:(void (^)(BOOL))arg1;
- (void)removeUpdateFromInstallLaterWithBundleID:(NSString *)arg1;
- (void)didFinishDownloadForUpdateWithItemIdentifier:(unsigned long long)arg1 didInstall:(BOOL)arg2;
- (void)willStartDownloadForUpdateWithIdentifier:(unsigned long long)arg1;
- (void)removeOSUpdateScanObserver:(id <ISOSUpdateScanObserver>)arg1;
- (void)addOSUpdateScanObserver:(id <ISOSUpdateScanObserver>)arg1;
- (void)startOSUpdateScanWithForceFullScan:(BOOL)arg1 reportProgressImmediately:(BOOL)arg2 launchedFromNotification:(BOOL)arg3 userHasSeenAllUpdates:(BOOL)arg4 checkForOtherUpdates:(BOOL)arg5;
- (void)unhideAllOSUpdatesWithReplyBlock:(void (^)(BOOL))arg1;
- (void)hideOSUpdatesWithProductKeys:(NSArray *)arg1 withReplyBlock:(void (^)(BOOL))arg2;
- (void)osUpdateScanInProgressWithReplyBlock:(void (^)(BOOL))arg1;
- (void)checkForUpdatesWithUserHasSeenUpdates:(BOOL)arg1 replyBlock:(void (^)(BOOL, NSArray *, NSError *))arg2;
- (void)cancelOSUpdates:(NSArray *)arg1;
- (void)removeOSUpdateProgressObserver:(id <ISOSUpdateProgressObserver>)arg1;
- (void)addOSUpdateProgressObserver:(id <ISOSUpdateProgressObserver>)arg1;
- (void)startAppUpdates:(NSArray *)arg1 andOSUpdates:(NSArray *)arg2 withDelegate:(id <ISUpdateDelegate>)arg3 replyBlock:(void (^)(BOOL, NSError *))arg4;
- (void)removeAvailableUpdatesObserver:(id <ISAvailableUpdatesObserver>)arg1;
- (void)addAvailableUpdatesObserver:(id <ISAvailableUpdatesObserver>)arg1;
- (void)incompatibleUpdatesWithReplyBlock:(void (^)(NSArray *))arg1;
- (void)availableUpdateWithItemIdentifier:(unsigned long long)arg1 replyBlock:(void (^)(CKUpdate *))arg2;
- (void)availableUpdatesWithReplyBlock:(void (^)(NSArray *))arg1;
- (void)availableUpdatesBadgeCountWithReplyBlock:(void (^)(unsigned long long))arg1;
- (void)requestVPPReceiptRenewalAtPath:(NSString *)arg1 bundleIdentifier:(NSString *)arg2 sandboxOptions:(NSDictionary *)arg3 replyBlock:(void (^)(BOOL, NSError *))arg4;
- (void)lookupAppleIDForApp:(CKSoftwareProduct *)arg1 replyBlock:(void (^)(NSString *))arg2;
- (void)shouldAllowAutoPushForBundleID:(NSString *)arg1 bundleVersion:(NSString *)arg2 replyBlock:(void (^)(BOOL))arg3;
- (void)renewReceiptForApplicationAtPath:(NSString *)arg1 withAppleID:(NSString *)arg2 password:(NSString *)arg3 forceSandbox:(BOOL)arg4 replyBlock:(void (^)(BOOL, NSError *))arg5;
- (void)renewReceiptForApplicationAtPath:(NSString *)arg1 withAppleID:(NSString *)arg2 password:(NSString *)arg3 forceSandbox:(BOOL)arg4 relaunchOnRenewal:(BOOL)arg5 replyBlock:(void (^)(BOOL, NSError *))arg6;
- (void)productAtPath:(NSString *)arg1 willBeUpdatedToBundleVersion:(NSString *)arg2 storeVersion:(NSNumber *)arg3;
- (void)productAtPath:(NSString *)arg1 wasUpdated:(BOOL)arg2 toBundleVersion:(NSString *)arg3 storeVersion:(NSNumber *)arg4;
- (void)httpPostBodyWithInstalledApps:(BOOL)arg1 bundledApps:(BOOL)arg2 conditionally:(BOOL)arg3 replyBlock:(void (^)(NSData *, BOOL, BOOL))arg4;
- (void)iconForApplicationWithBundeID:(NSString *)arg1 replyBlock:(void (^)(NSData *))arg2;
- (void)bundleInfoFromBundleAtPath:(NSString *)arg1 replyBlock:(void (^)(NSDictionary *))arg2;
- (void)productPathToUpgradeForBundleIdentifier:(NSString *)arg1 versionNumberString:(NSString *)arg2 replyBlock:(void (^)(NSString *))arg3;
- (void)isTrialVersionOfBundleIdentifier:(NSString *)arg1 replyBlock:(void (^)(BOOL))arg2;
- (void)receiptFromBundleAtPath:(NSString *)arg1 replyBlock:(void (^)(ISPurchaseReceipt *))arg2;
- (void)productAtPath:(NSString *)arg1 replyBlock:(void (^)(CKSoftwareProduct *))arg2;
- (void)performVPPReceiptRenewalIfNecessaryForDownload:(SSDownload *)arg1 replyBlock:(void (^)(BOOL, NSError *))arg2;
- (void)allProductsWithReplyBlock:(void (^)(NSArray *))arg1;
- (void)productForItemIdentifier:(unsigned long long)arg1 replyBlock:(void (^)(CKSoftwareProduct *))arg2;
- (void)productForBundleIdentifier:(NSString *)arg1 replyBlock:(void (^)(CKSoftwareProduct *))arg2;
@end

