//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ISAuthenticationChallenge : NSObject
{
    NSString *_localizedMessage;
    NSString *_localizedTitle;
}

@property(retain) NSString *localizedTitle; // @synthesize localizedTitle=_localizedTitle;
@property(retain) NSString *localizedMessage; // @synthesize localizedMessage=_localizedMessage;
- (void).cxx_destruct;
@property(readonly) BOOL userNameIsEmail;
@property(readonly) BOOL userNameIsEditable;
- (void)useCredential:(id)arg1;
@property(readonly) NSString *user;
@property(readonly) __weak id <NSURLAuthenticationChallengeSender> sender;
@property(readonly) NSString *password;
@property(readonly) BOOL hasPassword;
@property(readonly) long long failureCount;
- (void)cancelAuthentication;

@end

