//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ISDevice : NSObject
{
}

+ (BOOL)isBootedFromRecoveryPartition;
+ (id)osMajorVersionString;
+ (void)osVersionReturningMajor:(int *)arg1 minor:(int *)arg2 point:(int *)arg3;
+ (long long)availableDiskSpace;
+ (long long)availableSpaceOnDiskAtPath:(id)arg1;
+ (id)guid;

@end

