//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ISStoreAccount, NSArray, SSDownload, SSDownloadStatus;

@protocol ISDownloadQueueObserver
- (void)downloadQueueDidCheckServerDownloadQueueForAccount:(ISStoreAccount *)arg1 withDownloadCount:(long long)arg2 newDownloads:(NSArray *)arg3;
- (void)download:(SSDownload *)arg1 didUpdateStatus:(SSDownloadStatus *)arg2;
- (void)downloadQueueDidRemoveDownload:(SSDownload *)arg1 queueIsIdle:(BOOL)arg2;
- (void)downloadQueueDidAddDownload:(SSDownload *)arg1;
@end

