//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ISInvocationRecorder : NSObject
{
    id _target;
}

- (void).cxx_destruct;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)invokeInvocation:(id)arg1;
- (id)adjustedTargetForSelector:(SEL)arg1;
- (void)dealloc;
- (id)initWithTarget:(id)arg1;

@end

