//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <StoreFoundation/ISPropertyListProvider.h>

@interface ISJSONProvider : ISPropertyListProvider
{
}

- (BOOL)parseData:(id)arg1 returningError:(id *)arg2;

@end

