//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface ISOperationQueue : NSObject
{
    NSOperationQueue *_queue;
}

+ (id)mainQueue;
+ (BOOL)isActive;
- (void).cxx_destruct;
- (void)setSuspended:(BOOL)arg1;
- (void)setMaxConcurrentOperationCount:(long long)arg1;
- (id)operations;
- (void)cancelAllOperations;
- (void)addOperation:(id)arg1;
- (void)dealloc;
- (id)init;

@end

