//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSDictionary, NSError;

@protocol ISOSUpdateProgressObserver
- (void)osUpdates:(NSArray *)arg1 didFailWithError:(NSError *)arg2;
- (void)osUpdates:(NSArray *)arg1 didProgressWithState:(long long)arg2 percentComplete:(double)arg3 statusInfo:(NSDictionary *)arg4 includesCriticalUpdates:(BOOL)arg5 canCancel:(BOOL)arg6;
@end

