//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <StoreFoundation/ISOperation.h>

@class ISAuthenticationContext, ISDialog, NSNumber, NSURL;

@interface ISServerAuthenticationOperation : ISOperation
{
    NSNumber *_authenticatedAccountDSID;
    ISAuthenticationContext *_authenticationContext;
    ISDialog *_dialog;
    NSURL *_redirectURL;
}

+ (id)operationWithDialog:(id)arg1 storeClient:(id)arg2;
@property(retain) NSURL *redirectURL; // @synthesize redirectURL=_redirectURL;
@property(readonly) ISDialog *dialog; // @synthesize dialog=_dialog;
@property(retain) NSNumber *authenticatedAccountDSID; // @synthesize authenticatedAccountDSID=_authenticatedAccountDSID;
@property(retain) ISAuthenticationContext *authenticationContext; // @synthesize authenticationContext=_authenticationContext;
- (void).cxx_destruct;
- (BOOL)_shouldAuthenticateForButton:(id)arg1;
- (void)_sendClientToURL:(id)arg1;
- (BOOL)_handleSelectedButton:(id)arg1;
- (void)run;
- (id)initWithDialog:(id)arg1 storeClient:(id)arg2;
- (id)_authentciateReturningError:(id *)arg1;
- (id)_authenticationContext;

@end

