//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <StoreFoundation/ISAuthenticationChallenge.h>

@class NSString;

@interface ISStoreAuthenticationChallenge : ISAuthenticationChallenge
{
    long long _failureCount;
    BOOL _hasPassword;
    NSString *_password;
    id <NSURLAuthenticationChallengeSender> _sender;
    NSString *_user;
    BOOL _userNameIsEditable;
}

@property BOOL userNameIsEditable; // @synthesize userNameIsEditable=_userNameIsEditable;
@property(retain) NSString *user; // @synthesize user=_user;
@property __weak id <NSURLAuthenticationChallengeSender> sender; // @synthesize sender=_sender;
@property(retain) NSString *password; // @synthesize password=_password;
@property BOOL hasPassword; // @synthesize hasPassword=_hasPassword;
@property long long failureCount; // @synthesize failureCount=_failureCount;
- (void).cxx_destruct;
- (BOOL)userNameIsEmail;
- (id)init;

@end

