//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL;

@interface ISStoreVersion : NSObject
{
    NSURL *_redirectURL;
}

@property(retain, nonatomic) NSURL *redirectURL; // @synthesize redirectURL=_redirectURL;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

