//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSArray, NSData, NSDictionary, NSString, NSURL;

@interface ISURLRequest : NSObject <NSSecureCoding, NSCopying>
{
    NSData *_body;
    NSString *_method;
    NSDictionary *_queryStringDictionary;
    double _timeoutInterval;
    BOOL _retryAfterTimeout;
    NSArray *_urls;
    unsigned long long _cachePolicy;
    NSDictionary *_customHeaders;
    BOOL _resourceRequest;
    BOOL _preventsIdleSystemSleep;
    BOOL _suppressADIHeaders;
    BOOL _alwaysSendGUID;
}

+ (id)requestWithURL:(id)arg1;
+ (BOOL)supportsSecureCoding;
@property BOOL alwaysSendGUID; // @synthesize alwaysSendGUID=_alwaysSendGUID;
@property BOOL suppressADIHeaders; // @synthesize suppressADIHeaders=_suppressADIHeaders;
@property BOOL preventsIdleSystemSleep; // @synthesize preventsIdleSystemSleep=_preventsIdleSystemSleep;
@property(readonly) BOOL resourceRequest; // @synthesize resourceRequest=_resourceRequest;
@property(retain) NSDictionary *customHeaders; // @synthesize customHeaders=_customHeaders;
@property unsigned long long cachePolicy; // @synthesize cachePolicy=_cachePolicy;
@property(retain) NSArray *URLs; // @synthesize URLs=_urls;
@property BOOL retryAfterTimeout; // @synthesize retryAfterTimeout=_retryAfterTimeout;
@property double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(retain) NSDictionary *queryStringDictionary; // @synthesize queryStringDictionary=_queryStringDictionary;
@property(retain) NSString *method; // @synthesize method=_method;
@property(retain) NSData *body; // @synthesize body=_body;
- (void).cxx_destruct;
- (id)description;
- (void)setValue:(id)arg1 forQueryStringParameter:(id)arg2;
- (void)setValue:(id)arg1 forHeaderField:(id)arg2;
@property(readonly) NSURL *primaryURL;
- (id)newURLRequestWithURL:(id)arg1 storeAccount:(id)arg2 serviceProxy:(id)arg3;
- (BOOL)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)initWithURLRequest:(id)arg1;
- (id)init;

@end

