//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <StoreFoundation/ISOperation.h>

#import "NSURLConnectionDelegate.h"

@class ISDataProvider, ISURLRequest, NSCountedSet, NSDictionary, NSMutableData, NSString, NSURLConnection, NSURLRequest, NSURLResponse;

@interface ISURLOperation : ISOperation <NSURLConnectionDelegate>
{
    NSURLRequest *_activeURLRequest;
    NSURLConnection *_connection;
    NSMutableData *_dataBuffer;
    ISDataProvider *_dataProvider;
    long long _networkRetryCount;
    long long _contentRetryCount;
    NSCountedSet *_redirectURLs;
    ISURLRequest *_request;
    NSURLResponse *_response;
    BOOL _shouldSetCookies;
    unsigned long long _countedBytes;
    BOOL _checkForIncompleteFinish;
    BOOL _cancelIfNotAlreadyOnDisk;
    BOOL _fileWasAlreadyOnDisk;
    BOOL _shouldRetryOnNetworkError;
    NSDictionary *_conditionalConnectionProperties;
    CDUnknownBlockType _outputHandler;
}

+ (long long)operationType;
@property(copy) CDUnknownBlockType outputHandler; // @synthesize outputHandler=_outputHandler;
@property(copy) NSDictionary *conditionalConnectionProperties; // @synthesize conditionalConnectionProperties=_conditionalConnectionProperties;
@property BOOL shouldRetryOnNetworkError; // @synthesize shouldRetryOnNetworkError=_shouldRetryOnNetworkError;
@property(readonly) BOOL fileWasAlreadyOnDisk; // @synthesize fileWasAlreadyOnDisk=_fileWasAlreadyOnDisk;
@property BOOL cancelIfNotAlreadyOnDisk; // @synthesize cancelIfNotAlreadyOnDisk=_cancelIfNotAlreadyOnDisk;
@property BOOL checkForIncompleteFinish; // @synthesize checkForIncompleteFinish=_checkForIncompleteFinish;
@property(getter=_shouldSetCookies, setter=_setShouldSetCookies:) BOOL _shouldSetCookies; // @synthesize _shouldSetCookies;
@property(retain) NSURLResponse *response; // @synthesize response=_response;
@property(retain) ISDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
- (void).cxx_destruct;
- (void)_updateProgress;
- (void)_stopConnection;
- (void)_sendResponseToDelegate:(id)arg1;
- (void)_sendRequestToDelegate:(id)arg1;
- (void)_sendOutputToDelegate:(id)arg1;
- (void)_setActiveURLRequest:(id)arg1;
- (BOOL)_runWithURL:(id)arg1;
- (void)_run;
- (void)_retry;
- (id)_urlConnectionWithRequest:(id)arg1;
- (void)_logResponseBody:(id)arg1;
- (void)_logRequest:(id)arg1;
- (void)_logHeadersForRequest:(id)arg1;
- (id)_copyQueryStringDictionaryForRedirect:(id)arg1;
- (id)_copyAcceptLanguageString;
- (id)_activeURL;
- (id)_handleRedirectRequest:(id)arg1 response:(id)arg2;
- (void)_handleReceivedResponse:(id)arg1;
- (void)_handleReceivedData:(id)arg1;
- (void)_handleFinishedLoading;
- (id)_request;
- (void)connection:(id)arg1 conditionalRequirementsChanged:(BOOL)arg2;
- (id)connection:(id)arg1 willSendRequestForEstablishedConnection:(id)arg2 properties:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (BOOL)shouldFollowRedirectWithRequest:(id)arg1 returningError:(id *)arg2;
- (id)newRequestWithURL:(id)arg1;
- (void)handleResponse:(id)arg1;
- (BOOL)handleRedirectFromDataProvider:(id)arg1;
- (void)run;
@property(copy) ISURLRequest *request; // @synthesize request=_request;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property __weak id <ISURLOperationDelegate><ISOperationDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

