//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSError.h"

@interface NSError (ISAdditions)
+ (id)tooBigForDiskErrorWithCount:(long long)arg1;
- (BOOL)isFatalError;
- (BOOL)isEqual:(id)arg1 compareUserInfo:(BOOL)arg2;
- (id)errorBySettingValue:(id)arg1 forUserInfoKey:(id)arg2;
- (id)errorBySettingFatalError:(BOOL)arg1;
@end

