//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (ISAdditions)
+ (BOOL)_storeMovePath:(id)arg1 toPath:(id)arg2;
+ (BOOL)ensureDirectoryExists:(id)arg1;
+ (id)cacheDirectoryPathWithName:(id)arg1;
- (BOOL)writeReceiptString:(id)arg1 toPath:(id)arg2;
- (BOOL)isBootableVolume:(id)arg1;
- (BOOL)isUpdatableAtPath:(id)arg1;
- (BOOL)isInstallableAtPath:(id)arg1;
- (BOOL)isAppStoreAppAtPath:(id)arg1;
- (BOOL)isSignedFileAtPath:(id)arg1;
- (BOOL)isSignedByDeveloperFileAtPath:(id)arg1 withProgressHandler:(CDUnknownBlockType)arg2;
- (BOOL)isSignedByDeveloperFileAtPath:(id)arg1 basicCheck:(BOOL)arg2;
- (BOOL)isSignedByDeveloperFileAtPath:(id)arg1 basicCheck:(BOOL)arg2 progressHandler:(CDUnknownBlockType)arg3;
- (BOOL)isSignedByDeveloperFileAtPath:(id)arg1;
- (BOOL)isSignedByAppleFileAtPath:(id)arg1;
- (BOOL)isSignedByAppleFileAtPath:(id)arg1 withProgressHandler:(CDUnknownBlockType)arg2;
- (BOOL)isSignedByAppleFileAtPath:(id)arg1 basicCheck:(BOOL)arg2;
- (BOOL)isSignedByAppleFileAtPath:(id)arg1 basicCheck:(BOOL)arg2 progressHandler:(CDUnknownBlockType)arg3;
- (BOOL)_isFileSignedAtPath:(id)arg1 withRequirement:(struct __CFData *)arg2;
- (BOOL)_isFileSignedAtPath:(id)arg1 withRequirement:(struct __CFData *)arg2 basicCheck:(BOOL)arg3;
- (BOOL)_isFileSignedAtPath:(id)arg1 withRequirement:(struct __CFData *)arg2 basicCheck:(BOOL)arg3 progressHandler:(CDUnknownBlockType)arg4;
@end

