//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSHTTPURLResponse.h"

@interface NSHTTPURLResponse (ISAdditions)
- (long long)maxExpectedContentLength;
- (BOOL)getAppleMaxAge:(double *)arg1;
- (double)expirationInterval;
- (id)expirationDate;
- (id)_dateFromExpires;
- (BOOL)_getCacheControlMaxAge:(double *)arg1;
@end

