//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumber.h"

@interface NSNumber (SSAdditions)
+ (id)numberWithItemIdentifier:(unsigned long long)arg1;
- (unsigned long long)itemIdentifierValue;
- (id)initWithItemIdentifier:(unsigned long long)arg1;
@end

