//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (ISAdditions)
- (id)volumePath;
- (id)parameterStringByAppendingParameters:(id)arg1;
- (id)stripPassword;
- (id)copyUTF8StringOfLength:(unsigned long long)arg1;
@end

