//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSData, NSDictionary, NSNumber, NSString;

@protocol ReceiptInstallerProtocol
- (oneway void)setLastDoItLaterLogoutFailed:(BOOL)arg1;
- (oneway void)createWhatsNewOnlinePageViewedTimestamp;
- (oneway void)createWhatsNewNotificationTimestampWithSystemVersion:(NSString *)arg1;
- (oneway void)writeUpToDateInfo:(NSData *)arg1;
- (oneway void)createUpToDateFirstCheckinCookie;
- (oneway void)deleteVPPInviteFromPreferences;
- (oneway void)setAutoUpdateRestartRequiredEnabledPreference:(NSNumber *)arg1 majorOSVersion:(NSString *)arg2;
- (oneway void)setAutoUpdateEnabledPreference:(NSNumber *)arg1 majorOSVersion:(NSString *)arg2;
- (oneway void)removeCriticalUpdateTimeStamp;
- (oneway void)createCriticalUpdateTimeStamp;
- (oneway void)updateLockedFilePaths:(NSArray *)arg1 addOrDelete:(BOOL)arg2;
- (oneway void)removeApplicationAtPath:(NSString *)arg1;
- (oneway void)unlockApplicationsAtPaths:(NSArray *)arg1;
- (oneway void)lockApplicationAtPath:(NSString *)arg1;
- (oneway void)setIconData:(NSData *)arg1 forPlaceholderAtPath:(NSString *)arg2;
- (oneway void)createPlaceholderAtPath:(NSString *)arg1 fromPath:(NSString *)arg2 replyBlock:(void (^)(NSError *, NSString *))arg3;
- (oneway void)removePlaceholderAtPath:(NSString *)arg1;
- (oneway void)createPlaceholderAtPath:(NSString *)arg1 withData:(NSData *)arg2;
- (oneway void)writeAdoptionInfo:(NSData *)arg1;
- (oneway void)removeIAPProductAtPath:(NSString *)arg1;
- (oneway void)installReceiptWithParameters:(NSDictionary *)arg1 replyBlock:(void (^)(NSError *))arg2;
@end

