//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray;

@interface SSDownloadManifestResponse : NSObject <NSCoding>
{
    NSArray *_invalidDownloads;
    NSArray *_validDownloads;
}

- (void).cxx_destruct;
@property(retain) NSArray *validDownloads;
@property(retain) NSArray *invalidDownloads;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

