//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSValue;

@interface SSRequest : NSObject
{
    id <SSRequestDelegate> _delegate;
    NSString *_identifier;
    long long _state;
    NSValue *_callbackID;
}

+ (id)_newIdentifier;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak id <SSRequestDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_finish;
- (void)_failWithError:(id)arg1;
- (BOOL)issueRequestForIdentifier:(id)arg1 error:(id *)arg2;
- (BOOL)handleFinishResponse:(id)arg1 error:(id *)arg2;
- (void)handleDaemonExit;
- (void)callback:(id)arg1 connectionIsValid:(BOOL)arg2;
- (BOOL)send;
- (id)messageName;
@property(readonly) NSString *requestQueueSelectorName; // @dynamic requestQueueSelectorName;
- (id)requestInfo;
- (BOOL)start;
- (void)cancel;
- (void)dealloc;
- (id)init;

@end

