//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISAccountStoreObserver.h"

@interface CKAccountStoreClient : NSObject <ISAccountStoreObserver>
{
    CDUnknownBlockType _primaryAccountChangeObserver;
}

@property(copy) CDUnknownBlockType primaryAccountChangeObserver; // @synthesize primaryAccountChangeObserver=_primaryAccountChangeObserver;
- (void).cxx_destruct;
- (void)primaryAccountDidChange:(id)arg1;

@end

