//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDelegate.h"

@class ISAuthenticationContext, ISStoreClient, NSDictionary, NSString;

@interface CKAccountAuthentication : NSObject <NSURLConnectionDelegate>
{
    id <CKAccountAuthenticationDelegate> _delegate;
    NSString *_accountName;
    NSString *_password;
    NSDictionary *_serverResponseDictionary;
    ISAuthenticationContext *_context;
    long long _attempt;
    ISStoreClient *_storeClient;
}

@property(retain) ISStoreClient *storeClient; // @synthesize storeClient=_storeClient;
@property long long attempt; // @synthesize attempt=_attempt;
@property(retain) ISAuthenticationContext *context; // @synthesize context=_context;
@property(readonly) NSDictionary *serverResponseDictionary; // @synthesize serverResponseDictionary=_serverResponseDictionary;
@property(retain) NSString *password; // @synthesize password=_password;
@property(retain) NSString *accountName; // @synthesize accountName=_accountName;
@property id <CKAccountAuthenticationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stop;
- (BOOL)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

