//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface CKAppStoreLauncher : NSObject
{
    NSMutableDictionary *_validURLs;
}

+ (void)validateLaunchURL:(id)arg1 withResultBlock:(CDUnknownBlockType)arg2;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)launchAppStoreWithURL:(id)arg1;
- (id)_validateLaunchURL:(id)arg1;
- (id)init;

@end

