//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISServiceProxy, NSArray, NSPredicate;

@interface CKBookLibrary : NSObject
{
    long long _libraryType;
    NSArray *_sortDescriptors;
    NSPredicate *_searchPredicate;
    id <CKBookLibraryDelegate> _delegate;
    ISServiceProxy *_serviceProxy;
}

+ (BOOL)hasSampleWithItemIdentifier:(id)arg1 returningMetadata:(id *)arg2;
+ (id)shelfSortDescriptors;
+ (id)categorySortDescriptors;
+ (id)authorSortDescriptors;
+ (id)titleSortDescriptors;
@property(readonly) ISServiceProxy *serviceProxy; // @synthesize serviceProxy=_serviceProxy;
@property(nonatomic) __weak id <CKBookLibraryDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy) NSPredicate *searchPredicate; // @synthesize searchPredicate=_searchPredicate;
@property(copy) NSArray *sortDescriptors; // @synthesize sortDescriptors=_sortDescriptors;
@property(readonly) long long libraryType; // @synthesize libraryType=_libraryType;
- (void).cxx_destruct;
- (void)pollForPurchasedBooks;
- (void)removeObserver:(id)arg1;
- (id)addObserver:(id)arg1;
- (id)addObserverOfType:(long long)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)bookWithItemIdentifier:(unsigned long long)arg1;
- (id)objectInBooksAtIndex:(unsigned long long)arg1;
- (id)booksAtIndexes:(id)arg1;
- (id)_willReturnBooks:(id)arg1;
- (unsigned long long)countOfBooks;
- (id)_requestInfo;
- (id)initWithLibraryType:(long long)arg1;

@end

