//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSObject<OS_dispatch_queue>, NSObject<OS_xpc_object>;

@interface CKClientDispatch : NSObject
{
    NSObject<OS_xpc_object> *serviceXPCConnection;
    NSLock *serviceConnectionLock;
    NSObject<OS_xpc_object> *agentXPCConnection;
    NSLock *agentConnectionLock;
    NSObject<OS_dispatch_queue> *mQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)cancelCallback:(id)arg1;
- (id)_syncInvokeSelector:(id)arg1 ofClass:(id)arg2 withObject:(id)arg3;
- (id)invokeSelector:(id)arg1 ofClass:(id)arg2 withObject:(id)arg3 callbackQueue:(id)arg4 callbackBlock:(CDUnknownBlockType)arg5;
- (void)invokeSelector:(id)arg1 ofClass:(id)arg2 withObject:(id)arg3 replyQueue:(id)arg4 replyBlock:(CDUnknownBlockType)arg5;
- (void)invokeSelector:(id)arg1 ofClass:(id)arg2 replyQueue:(id)arg3 replyBlock:(CDUnknownBlockType)arg4;
- (void)invokeSelector:(id)arg1 ofClass:(id)arg2 withObject:(id)arg3;
- (void)invokeSelector:(id)arg1 ofClass:(id)arg2;
- (void)dealloc;
- (id)init;
- (id)_sendMessage:(id)arg1 callbackQueue:(id)arg2 callbackBlock:(CDUnknownBlockType)arg3;
- (void)_sendMessage:(id)arg1 replyQueue:(id)arg2 replyBlock:(CDUnknownBlockType)arg3;

@end

