//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISBookLibraryObserver.h"

@interface CKDAAPPurchaseHistoryClient : NSObject <ISBookLibraryObserver>
{
    CDUnknownBlockType _observerBlock;
}

@property(copy) CDUnknownBlockType observerBlock; // @synthesize observerBlock=_observerBlock;
- (void).cxx_destruct;
- (void)bookLibraryHasAdded:(id)arg1 changed:(id)arg2 removed:(id)arg3;

@end

