//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CKDaemonPreferencesController : NSObject
{
}

+ (id)sharedInstance;
- (void)_preferencesChanged:(id)arg1;
- (void)postPreferencesChangedNotification;
- (void)stopObservingPreferenceChanges;
- (void)startObservingPreferenceChanges;

@end

