//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ISServiceProxy;

@interface CKDAAPPurchaseHistory : NSObject
{
    ISServiceProxy *_serviceProxy;
}

@property(readonly) ISServiceProxy *serviceProxy; // @synthesize serviceProxy=_serviceProxy;
- (void).cxx_destruct;
- (void)pollForPurchasedItems:(BOOL)arg1;
- (void)removeObserver:(id)arg1;
- (id)addObserver:(id)arg1;
- (id)addObserverWithBlock:(CDUnknownBlockType)arg1;
- (id)purchasedItems;
- (id)initWithStoreClient:(id)arg1;

@end

