//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CommerceKit/CKServiceInterface.h>

@class NSLock;

@interface CKDialogController : CKServiceInterface
{
    NSLock *_lock;
    id <ISUIHostProtocol> _delegate;
}

+ (id)sharedDialogController;
- (void).cxx_destruct;
- (void)setDelegate:(id)arg1;
- (id)initWithStoreClient:(id)arg1;

@end

