//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISDownloadQueueObserver-Protocol.h"

@interface CKDownloadQueueClient : NSObject <ISDownloadQueueObserver>
{
    long long _downloadTypesMask;
//    CDUnknownBlockType _observerBlock;
}

//@property(copy) CDUnknownBlockType observerBlock; // @synthesize observerBlock=_observerBlock;
@property long long downloadTypesMask; // @synthesize downloadTypesMask=_downloadTypesMask;
//- (void).cxx_destruct;
- (void)downloadQueueDidCheckServerDownloadQueueForAccount:(id)arg1 withDownloadCount:(long long)arg2 newDownloads:(id)arg3;
- (void)download:(id)arg1 didUpdateStatus:(id)arg2;
- (void)downloadQueueDidRemoveDownload:(id)arg1 queueIsIdle:(BOOL)arg2;
- (void)downloadQueueDidAddDownload:(id)arg1;

@end

