//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSString;
@class CKItemLookupResponse;

@interface CKItemLookupRequest : NSObject
{
    NSArray *_bundleIdentifiers;
    NSArray *_adamIdentifiers;
    BOOL _platformOverride;
    NSString *_keyProfile;
    NSString *_preferredLanguage;
//    CDUnknownBlockType _lookupCallbackBlock;
}

@property(retain, nonatomic) NSString *preferredLanguage; // @synthesize preferredLanguage=_preferredLanguage;
@property BOOL platformOverride; // @synthesize platformOverride=_platformOverride;
//- (void).cxx_destruct;
- (id)parameters;
- (BOOL)start;
- (BOOL)startWithLookupBlock:(void(^)(CKItemLookupResponse *, NSError *))block;
- (id)initWithBundleIdentifiers:(NSArray*)arg1 adamIDs:(NSArray *)arg2 keyProfile:(NSString *)arg3;
@end

