//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CommerceKit/CKAccountAuthentication.h>

#import "ISStoreURLOperationDelegate.h"

@class ISStoreURLOperation, NSMutableData, NSString, NSURL;

@interface CKiTunesAppleIDAuthentication : CKAccountAuthentication <ISStoreURLOperationDelegate>
{
    NSURL *_url;
    NSMutableData *_receivedData;
    ISStoreURLOperation *_loadOperation;
}

- (void).cxx_destruct;
- (void)stop;
- (BOOL)start;
- (void)operation:(id)arg1 willSendRequest:(id)arg2;
- (void)operation:(id)arg1 didReceiveResponse:(id)arg2;
- (void)operation:(id)arg1 finishedWithOutput:(id)arg2;
- (id)_encodeString:(id)arg1;
- (id)_requestBodyDataWithAdditionalQueryParameters:(id)arg1;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

