//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary;

@interface CKItemLookupResponse : NSObject
{
    NSDictionary *_responseDictionary;
}

//- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *resultDictionary; // @dynamic resultDictionary;
@property(readonly, nonatomic) unsigned long long responseCount; // @dynamic responseCount;
- (id)initWithDictionary:(id)arg1;

@end

