//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CommerceKit/CKServiceInterface.h>

@interface CKMachineAuthorization : CKServiceInterface
{
}

+ (id)sharedMachineAuthorization;
- (void)deauthorizeMachineWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)authorizeMachineWithAppleID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

@end

