//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CommerceKit/CKServiceInterface.h>
#import <StoreFoundation/SSPurchase.h>

@class SSPurchaseResponse;

@interface CKPurchaseController : CKServiceInterface
{
    NSMutableArray *_purchases;
    NSMutableArray *_rejectedPurchases;
    NSArray *_adoptionEligibleItems;
    NSNumber *_adoptionServerStatus;
    NSNumber *_adoptionErrorNumber;
//    CDUnknownBlockType _dialogHandler;
}

+ (void)setNeedsSilentMachineAuthorization:(BOOL)arg1;
+ (CKPurchaseController *)sharedPurchaseController;
- (void)performPurchase:(SSPurchase *)purchase withOptions:(NSUInteger)options completionHandler:(void(^)(SSPurchase *, BOOL, NSError*, SSPurchaseResponse *))completionHandler;

//@property(copy) CDUnknownBlockType dialogHandler; // @synthesize dialogHandler=_dialogHandler;
//- (BOOL)adoptionCompletedForBundleID:(id)arg1;
//- (void)_performVPPReceiptRenewal;
//- (void)checkServerDownloadQueue;
//- (id)purchaseInProgressForProductID:(id)arg1;
//- (id)purchasesInProgress;
//- (void)cancelPurchaseWithProductID:(id)arg1;
//- (void)resumeDownloadForPurchasedProductID:(id)arg1;
//- (void)startPurchases:(NSArray<SSPurchase *> *)purchases shouldStartDownloads:(BOOL)downloads eventHandler:(CDUnknownBlockType)arg3;
//- (void)checkInstallRequirementsAtURL:(id)arg1 productID:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;

@end

