//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CommerceKit/CKServiceInterface.h>

@interface CKPushNotificationManager : CKServiceInterface
{
    id _delegate;
}

+ (id)sharedManager;
@property __weak id <CKPushNotificationManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)isRegisteredForAccount:(id)arg1 andMask:(long long)arg2;
- (BOOL)isRegisteredForAccount:(id)arg1;
- (BOOL)stopAtSignOut;
- (void)disableAutoDownloadAtSignOutWithCompletionHandler:(CDUnknownBlockType)arg1;
- (BOOL)startAtSignIn;
- (void)enableAutoDownloadAtSignInWithCompletionHandler:(CDUnknownBlockType)arg1;
- (BOOL)stop;
- (void)disableAutoDownloadWithCompletionHandler:(CDUnknownBlockType)arg1;
- (BOOL)start;
- (void)enableAutoDownloadWithCompletionHandler:(CDUnknownBlockType)arg1;
- (BOOL)checkEnabledMediaTypes;
- (void)getEnabledMedaTypesWithCompletionHandler:(CDUnknownBlockType)arg1;
- (BOOL)registerPushToken;
- (void)registerDeviceTokenWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)_writeAutoDownloadEnabled:(long long)arg1 forAccount:(id)arg2;
- (BOOL)_isAutoDownloadEnabledForAccount:(id)arg1;
- (void)_updateRegisteredDSIDsPreferences:(id)arg1 forDSID:(id)arg2;
- (BOOL)_setRegisteredDSIDsPreferences:(id)arg1;
- (id)_registeredDSIDsPreferences;
- (void)_sendChangedToDelegate;
- (void)_sendSuccessToDelegate;
- (void)_sendErrorToDelegate:(id)arg1;

@end

