//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSRequest.h"

@class ISServiceProxy, NSArray;

@interface CKRestoreDownloadsRequest : SSRequest
{
    NSArray *_archivedFiles;
    ISServiceProxy *_serviceProxy;
    BOOL _userInitiated;
}

@property BOOL userInitiated; // @synthesize userInitiated=_userInitiated;
- (void).cxx_destruct;
- (BOOL)issueRequestForIdentifier:(id)identifier error:(NSError **)error;
- (id)initWithArchivedFiles:(id)arg1;

@end

