//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CKServiceInterface.h"
#import "CKSoftwareProduct.h"

@class NSLock, NSMutableArray;

@interface CKSoftwareMap : CKServiceInterface
{
    NSMutableArray *_observers;
    NSLock *_observersLock;
}

+ (CKSoftwareMap *)sharedSoftwareMap;
- (id)adaptableBundleIdentifiers;
- (BOOL)adoptionCompletedForBundleID:(id)arg1 adoptingDSID:(out id *)arg2 appleID:(out id *)arg3;
- (id)updateRequestBodyData:(char *)arg1 includeInstalledApps:(BOOL)arg2 includeBundledApps:(BOOL)arg3 conditionally:(BOOL)arg4 hadUnadoptedApps:(out char *)arg5;
- (id)iconForApplicationWithBundeID:(id)arg1;
- (id)bundleInfoFromBundleAtPath:(id)arg1;
- (BOOL)isTrialVersionOfBundleIdentifier:(id)arg1;
- (id)receiptFromBundleAtPath:(id)arg1;
- (id)productForPath:(id)arg1;
- (NSArray<CKSoftwareProduct *>*)allProducts;
- (CKSoftwareProduct *)productForItemIdentifier:(unsigned long long)arg1;
- (CKSoftwareProduct *)productForBundleIdentifier:(NSString *)arg1;
- (void)removeProductsObserver:(id)arg1;
//- (id)addProductsObserver:(CDUnknownBlockType)arg1 queue:(id)arg2;
- (id)initWithStoreClient:(id)arg1;

@end

