//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol ISAvailableUpdatesObserver
- (void)availableUpdatesDidChangedWithUpdates:(NSArray *)arg1 osUpdates:(NSArray *)arg2 badgeCount:(unsigned long long)arg3;
@end

