//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol ISBookLibraryObserver
- (void)bookLibraryHasAdded:(NSArray *)arg1 changed:(NSArray *)arg2 removed:(NSArray *)arg3;
@end

