//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISOperation.h"

#import "ISURLOperationDelegate.h"

@class ISPropertyListProvider, NSDictionary, NSString, NSURL;

@interface ISProcessPropertyListOperation : ISOperation <ISURLOperationDelegate>
{
    ISPropertyListProvider *_dataProvider;
    NSDictionary *_propertyList;
    NSURL *_propertyListURL;
    CDUnknownBlockType _preParserBlock;
}

@property(retain) ISPropertyListProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
- (void).cxx_destruct;
- (void)operation:(id)arg1 failedWithError:(id)arg2;
- (void)operation:(id)arg1 finishedWithOutput:(id)arg2;
- (void)run;
- (id)initWithPropertyListAtURL:(id)arg1 withPreParserBlock:(CDUnknownBlockType)arg2 storeClient:(id)arg3;
- (id)initWithPropertyList:(id)arg1 storeClient:(id)arg2;
- (id)initWithStoreClient:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

