//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSSet, NSString, NSURLCache;

@interface ISURLCache : NSObject
{
    NSURLCache *_cache;
    NSArray *_clientIdentifiers;
    NSSet *_fileExtensions;
    NSString *_persistentIdentifier;
    NSArray *_urlPatterns;
}

+ (id)persistentIdentifierFromPropertyList:(id)arg1;
+ (id)cacheDirectoryPath;
@property(readonly) NSString *persistentIdentifier; // @synthesize persistentIdentifier=_persistentIdentifier;
- (void).cxx_destruct;
- (BOOL)_urlStringMatchesURLPatterns:(id)arg1;
- (BOOL)_urlStringMatchesFileExtensions:(id)arg1;
- (BOOL)_parseURLPatternCriteriaFromPropertyList:(id)arg1;
- (BOOL)_parseFileExtensionCriteriaFromPropertyList:(id)arg1;
- (BOOL)_parseCriteriaFromPropertyList:(id)arg1;
- (BOOL)_parseClientCriteriaFromPropertyList:(id)arg1;
- (void)storeCachedResponse:(id)arg1 forRequest:(id)arg2;
- (void)saveMemoryCacheToDisk;
- (void)removeCachedResponseForRequest:(id)arg1;
- (void)removeAllCachedResponses;
- (void)purgeMemoryCache;
@property(readonly, nonatomic) unsigned long long memoryCapacity;
@property(readonly, nonatomic) unsigned long long diskCapacity;
@property(readonly, nonatomic) unsigned long long currentMemoryUsage;
@property(readonly, nonatomic) unsigned long long currentDiskUsage;
- (id)cachedResponseForRequest:(id)arg1;
- (BOOL)reloadWithPropertyList:(id)arg1;
- (BOOL)isUsableByClientWithIdentifier:(id)arg1;
- (BOOL)criteriaMatchesRequest:(id)arg1;
- (id)initWithPropertyList:(id)arg1;
- (id)init;

@end

