//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ISURLBagContext : NSObject
{
    unsigned long long _bagType;
}

+ (id)contextWithBagType:(unsigned long long)arg1;
@property unsigned long long bagType; // @synthesize bagType=_bagType;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

