//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, NSString;

@protocol MBSetupAssistantDelegateConfiguration
- (void)completeSetupWithResponse:(NSDictionary *)arg1 handler:(void (^)(BOOL, NSError *))arg2;
- (NSDictionary *)delegateSetupRequest;
- (NSString *)delegateIdentifier;

@optional
- (void)terminateSetupCompletion;
- (NSString *)delegateAccountInformation;
- (void)completeSetupWithResponse:(NSDictionary *)arg1 context:(long long)arg2 handler:(void (^)(BOOL, NSError *))arg3;
@end

