//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CommerceKit/SSURLRequestProperties.h>

@class NSData, NSDictionary, NSString, NSURL;

@interface SSMutableURLRequestProperties : SSURLRequestProperties
{
}

- (void)setValue:(id)arg1 forRequestParameter:(id)arg2;
- (void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2;
@property(retain) NSURL *URL; // @dynamic URL;
@property(copy) NSString *URLBagKey; // @dynamic URLBagKey;
@property double timeoutInterval; // @dynamic timeoutInterval;
@property(copy) NSDictionary *requestParameters; // @dynamic requestParameters;
@property(getter=isITunesStoreRequest) BOOL ITunesStoreRequest; // @dynamic ITunesStoreRequest;
@property(copy) NSString *HTTPMethod; // @dynamic HTTPMethod;
@property(copy) NSDictionary *HTTPHeaders; // @dynamic HTTPHeaders;
@property(copy) NSData *HTTPBody; // @dynamic HTTPBody;
@property(copy) NSString *clientIdentifier; // @dynamic clientIdentifier;
@property unsigned long long cachePolicy; // @dynamic cachePolicy;
@property long long allowedRetryCount; // @dynamic allowedRetryCount;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

