//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSNumber, NSString;

@interface SSRemoteNotification : NSObject
{
    NSDictionary *_userInfo;
}

- (void).cxx_destruct;
- (id)_valueForAlertKey:(id)arg1;
@property(readonly, nonatomic) NSDictionary *notificationUserInfo;
- (id)valueForKey:(id)arg1;
@property(readonly, nonatomic) NSString *soundFileName;
@property(readonly, nonatomic) id badgeValue;
@property(readonly, nonatomic) NSString *alertTitleString;
@property(readonly, nonatomic) NSString *alertOKString;
@property(readonly, nonatomic) NSString *alertCancelString;
@property(readonly, nonatomic) NSString *alertBodyString;
@property(readonly, nonatomic) NSNumber *targetDSID;
@property(readonly, nonatomic) long long actionType;
- (id)initWithNotificationUserInfo:(id)arg1;

@end

