#!/bin/bash -e
#
# script/archive
# mas
#
# Compresses artifacts so the can be archived more easily.
#

echo "==> 🗜️ Compressing mas"
zip .build/mas.zip .build/apple/Products/Release/mas

echo "==> 🔢 File Hash"
shasum -a 256 .build/mas.zip
