#!/bin/bash -e
#
# script/bootstrap
# mas
#
# Installs gem tools, installs Swift dependencies via CocoaPods and sorts
# the Xcode project file references.
#

main() {
  script/clean

  echo "==> 👢 Bootstrapping"

  # Install ruby tools
  bundle install

  # Skip Homebrew when running on Jenkins
  if [[ $USER != "jenkins" ]]; then
    # Install Mint and shellcheck
    brew bundle install --no-upgrade --verbose
  fi

  # Download and build project dependencies
  carthage bootstrap --platform macOS --cache-builds --verbose
}

main
