#!/bin/bash -e
#
# script/bootstrap
# mas
#
# Installs development dependencies and builds project dependencies.
#

main() {
  script/clean

  echo "==> 👢 Bootstrapping"

  # Install Ruby tools
  bundle install

  # Install Homebrew tools
  rm -f Brewfile.lock.json
  brew bundle install --no-upgrade --verbose
}

main
