#!/bin/bash -e
#
# script/bootstrap
# mas
#
# Installs gem tools, installs Swift dependencies via CocoaPods and sorts
# the Xcode project file references.
#

main() {
  script/clean

  echo "==> 👢 Bootstrapping"

  # Install ruby tools
  bundle install

  # Install Mint and shellcheck
  brew bundle install --verbose

  # Set up mint cache to be relative to user HOME
  export MINT_PATH=~/.mint/cache
  mkdir -p $MINT_PATH
  mint bootstrap --verbose

  # Download and build project dependencies
  carthage bootstrap --platform macOS --cache-builds

  # Old Xcode project sort script used for CocoaSeeds
  script/sort
}

main
