#!/bin/bash -ex
#
# script/bottle
# mas
#
# Builds bottles of Homebrew formula.
#

mkdir -p build
pushd build

brew uninstall \
    --force mas

# FIXME: Linker errors stop the script
brew install \
    --build-bottle \
    --force \
    mas

brew bottle \
    --verbose \
    --no-rebuild \
    --root-url=https://dl.bintray.com/phatblat/mas-bottles \
    mas

# bottle command output
# ==> Bottling mas--1.4.1.mojave.bottle.tar.gz...
# tar cf /Volumes/ThunderBay/Users/phatblat/dev/macos/mas/build/mas--1.4.1.mojave.bottle.tar mas/1.4.1
# gzip -f mas-bottle.tar
# ==> Detecting if mas--1.4.1.mojave.bottle.tar.gz is relocatable...
# ./mas--1.4.1.mojave.bottle.tar.gz
# bottle do
#     root_url "https://dl.bintray.com/phatblat/mas-bottles"
#     cellar :any_skip_relocation
#     sha256 "4625af81ccde47c61ecc7940e3560a78cd860714619cc48617afe1477211aa45" => :mojave
# end

# Bottle will have name like mas--1.4.1.mojave.bottle.tar.gz
bottle_name=$(ls -1 mas--*.bottle.tar.gz)
ls -l "$bottle_name"

cp "$bottle_name" "${bottle_name/mojave/high_sierra}"
cp "$bottle_name" "${bottle_name/mojave/sierra}"
cp "$bottle_name" "${bottle_name/mojave/el_capitan}"
cp "$bottle_name" "${bottle_name/mojave/yosemite}"

sha=$(shasum --algorithm 256 "$bottle_name" | cut -d' ' -f1)
echo "Bottle hash: $sha"

# TODO: Write bottle dsl block to formula

popd build
