#!/bin/bash -e
#
# script/build_artifacts
# mas
#
# Runs all related scripts for generating all artifacts.
#

VERSION=$(script/version)

echo "Updating mas $VERSION Homebrew formula"

script/brew_formula_update
script/bottle
