#!/bin/bash -e
#
# script/brew_core_update
# mas
#
# Updates mas Homebrew core formula:
# https://github.com/Homebrew/homebrew-core/blob/master/Formula/m/mas.rb
#
# brew bump-formula-pr --help
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

function usage {
  printf $'Usage: brew_core_update [--dry-run]\n  --dry-run flag enables dry run mode\n' >&2
  exit 1
}

# Parse arguments for --dry-run flag
case "${#}" in
0)
  dry_run=
  ;;
1)
  if [[ "${1}" = --dry-run ]]; then
    dry_run=--dry-run
  else
    usage
  fi
  ;;
*)
  usage
  ;;
esac

version_tag="v$(script/version)"
revision="$(git rev-parse "${version_tag}")"

printf $'==> 🧪%s Updating mas homebrew-core formula to version tag %s @ revision %s\n' "${dry_run:+ DRY RUN}" "${version_tag}" "${revision}"

brew bump-formula-pr \
  --tag "${version_tag}" \
  --revision "${revision}" \
  --fork-org mas-cli \
  --no-browse \
  --online \
  --strict \
  --verbose \
  ${dry_run} \
  mas
