#!/bin/bash -ex
#
# script/brew_tap_update
# mas
#
# Updates mas custom tap formula:
# https://github.com/mas-cli/homebrew-tap/blob/main/Formula/mas.rb
#

function usage {
  echo "Usage: brew_tap_update [<version_tag> [<sha1_hash>]]"
  echo "  version will be inferred using version script if not provided"
  echo "  sha will be inferred from the current commit if not provided"
  exit 1
}

# Max 2 arguments
if [[ "${#}" -gt 2 ]]; then
  usage 1>&2
fi

# arg 1 - version tag
MAS_VERSION="${1:-"v$(script/version)"}"

echo "MAS_VERSION: ${MAS_VERSION}"

# arg 2 - revision (commit hash)
# If arg 2 wasn't supplied or is empty, obtain revision from ${MAS_VERSION} version tag
REVISION="${2:-"$(git rev-parse "${MAS_VERSION}")"}"

echo "REVISION: ${REVISION}"

# Build in mas project
script/bottle
