#!/bin/bash
#
# script/brew_release_validate
# mas
#
# Validates the mas formula
# https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-contribute-a-fix-to-the-foo-formula
#

brew uninstall --force mas
brew install --build-from-source mas
brew test mas
brew audit --strict mas
brew style mas
