#!/bin/bash
#
# script/brew_release_validate
# mas
#
# Validates the mas formula
# https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-contribute-a-fix-to-the-foo-formula
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

brew uninstall --force mas
brew install --build-from-source mas
brew test mas
brew audit --strict mas
brew style mas
