#!/bin/bash -eu
#
# script/build
# mas
#
# Builds the Swift Package.
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

# Build for the host architecture by default.
if [[ "${#}" -ge 1 && "${1}" == '--universal' ]]; then
  ARCH=(
    --arch arm64
    --arch x86_64
  )
else
  ARCH=()
fi

# Disable the manifest cache.
if [[ "$(swift build --help)" =~ manifest-cache ]]; then
  CACHE=(--manifest-cache none)
else
  CACHE=()
fi

echo "==> 🏗️ Building mas $(script/version --write)"
swift build \
  --configuration release \
  "${ARCH[@]+"${ARCH[@]}"}" \
  --disable-sandbox \
  "${CACHE[@]+"${CACHE[@]}"}"
