#!/bin/bash -e

main() {
  build

  # If this is a tagged build we are going to relase
  if [[ ! -z $TRAVIS_TAG ]]; then
    archive
  fi
}

build() {
  xcodebuild -project "mas-cli.xcodeproj" -scheme mas-cli clean build | xcpretty -c
}

archive() {
  xcodebuild -project "mas-cli.xcodeproj" -scheme mas-cli -archivePath mas.xcarchive archive | xcpretty -c
}

main
