#!/bin/bash -e
#
# script/build
# mas
#
# Builds the Swift Package.
#

script/clean
script/lint

echo "==> 🏗️ Building mas ($(script/version))"
swift build --configuration release --arch arm64 --arch x86_64
