#!/bin/bash -e
#
# script/build_artifacts
# mas
#
# Runs all related scripts for generating all artifacts.
#

MAS_VERSION="$(script/version)"

echo "Building mas ${MAS_VERSION} artifacts"

script/clean
script/build --universal
script/package
