#!/bin/bash -e
#
# script/build_artifacts
# mas
#
# Runs all related scripts for generating all artifacts.
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

printf $'==> 👑 Building mas %s artifacts\n' "$(script/version)"

script/clean
script/build --universal
script/package
