#!/bin/bash -e
#
# script/clean
# mas
#
# Deletes the build and temp install directories.
#

BUILD_DIR=build
INSTALL_DIR=/tmp/mas-cli.dst

main() {
  rm -rf Carthage/Build
  rm -rf ${BUILD_DIR:?}
  rm -rf ${INSTALL_DIR:?}
}

main
