#!/bin/zsh -efu
#
# script/clean
# mas
#
# Deletes the build directory.
#

mas_dir="${0:a:h:h}"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

swift package clean
swift package reset
