#!/bin/bash -ex
#
# script/clean
# mas
#
# Deletes the build and temp installdirectories.
#

BUILD_DIR=build
INSTALL_DIR=/tmp/mas-cli.dst

main() {
  rm -rf ${BUILD_DIR:?}
  rm -rf ${INSTALL_DIR:?}
}

main
