#!/bin/bash -e
#
# script/install
# mas
#
# Installs mas into PREFIX.
#
# NOTE: This script is called by the mas Homebrew formula so it has only system
# dependencies aside from Swift.
# https://github.com/Homebrew/homebrew-core/blob/master/Formula/mas.rb
#

ARCH=$(uname -m)
RELEASE=.build/${ARCH}-apple-macosx/release
VERSION=$(script/version)

if [[ $(uname -m) == 'arm64' ]]; then
  PREFIX=/opt/homebrew
else
  PREFIX=/usr/local
fi

while test -n "$1"; do
  if [[ "$1" == '--universal' ]]; then
    ARCH=universal
    RELEASE=.build/apple/Products/Release
  else
    # Override default prefix path with optional arg
    PREFIX="$1"
  fi

  shift
done

echo "==> 📲 Installing mas ($VERSION) for $ARCH to $PREFIX"
ditto -v \
  "$RELEASE/mas" \
  "$PREFIX/bin/"
