#!/bin/bash -e

PREFIX=/usr/local
INSTALL_TEMPORARY_FOLDER=/tmp/mas-cli.dst

echo "==> 📲 Installing mas to $PREFIX"

xcodebuild install

pushd "$INSTALL_TEMPORARY_FOLDER"

mkdir -p "$PREFIX/Frameworks/"

mv -v \
    Frameworks/MasKit.framework \
    "$PREFIX/Frameworks/"

mv -f \
    bin/mas \
    "$PREFIX/bin/"

popd
