#!/bin/bash -e
#
# script/lint
# mas
#
# Linting checks for development and CI.
#

echo "==> 🚨 Linting mas"

echo "--> 🌳 Git"
git diff --check

echo
echo "--> 🕊️ Swift"
swiftlint lint --strict

echo
echo "--> 📜 Bash"
shfmt -i 2 -l -w contrib/ script/
