#!/bin/bash -ex
#
# script/package_install
# mas
#
# Runs the installer command using sudo to install the mas package.
#

IDENTIFIER=com.mphys.mas-cli

echo "==> 📲 Installing mas"

sudo installer \
    -pkg build/mas.pkg \
    -target /

pkgutil --pkg-info "$IDENTIFIER"

pkgutil --files "$IDENTIFIER"
