#!/bin/bash -e
#
# script/package_install
# mas
#
# Installs the mas distribution package. Requires sudo access.
#

IDENTIFIER=com.mphys.mas-cli

echo "==> 📲 Installing mas"

sudo installer \
  -pkg .build/mas.pkg \
  -target /

pkgutil --pkg-info "${IDENTIFIER}"

pkgutil --files "${IDENTIFIER}"
