#!/bin/bash -ex

set -o pipefail && \
    xcodebuild install \
    | bundle exec xcpretty --color

pushd build

echo "==> 🗜️ Compressing mas.xcarchive"
zip -r mas.xcarchive.zip mas.xcarchive

echo "==> ️🗜️ Compressing binary and framework"
pushd mas.xcarchive/Products
zip -r \
    mas-cli.zip \
    bin/mas \
    Frameworks/MasKit.framework
mv mas-cli.zip ../../
popd

echo "==> 📦 Assemble an installer package"
IDENTIFIER=com.mphys.mas-cli
COMPONENTS_PLIST=../Homebrew/Components.plist
DISTRIBUTION_PLIST=../Homebrew/Distribution.plist
INSTALL_TEMPORARY_FOLDER=/tmp/mas-cli.dst
INTERNAL_PACKAGE=mas_temp.pkg
OUTPUT_PACKAGE=mas.pkg
VERSION_STRING=1.1.1

tree "$INSTALL_TEMPORARY_FOLDER"

pkgbuild \
    --component-plist "$COMPONENTS_PLIST" \
    --identifier "$IDENTIFIER" \
    --install-location "/" \
    --root "$INSTALL_TEMPORARY_FOLDER" \
    --version "$VERSION_STRING" \
    "$INTERNAL_PACKAGE"

productbuild \
    --distribution "$DISTRIBUTION_PLIST" \
    --package-path "$INTERNAL_PACKAGE" \
    "$OUTPUT_PACKAGE"

echo "==> 🔢 Files Hashes"
shasum -a 256 mas-cli.zip mas.xcarchive.zip mas.pkg

popd
