#!/bin/bash -e
#
# script/package_install
# mas
#
# Installs the mas distribution package. Requires sudo access.
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

IDENTIFIER=com.mphys.mas-cli

echo "==> 📲 Installing mas"

sudo installer \
  -pkg .build/mas.pkg \
  -target /

pkgutil --pkg-info "${IDENTIFIER}"

pkgutil --files "${IDENTIFIER}"
