#!/bin/zsh -Ndefgku
#
# script/setup_workflow_repo
# mas
#
# Sets up the repo for use in a GitHub workflow.
#

. "${0:a:h}/_setup_script"

for branch in "${(f)"$(git for-each-ref refs/remotes/origin --format='%(if)%(symref)%(then)%(else)%(refname:strip=-1)%(end)')":#}"; do
	git branch --track "${branch}" "origin/${branch}" >/dev/null 2>&1 || true
done
