#!/bin/bash
#
# script/sort
# mas
#
# Invokes the sort.pl script on the Xcode project.
#

main() {
    echo "==> 📶 Sorting project files"
    sort_project
}

sort_project() {
    perl script/sort.pl mas-cli.xcodeproj/project.pbxproj
}

main
