#!/bin/bash
#
# script/sort
# mas
#
# Invokes the sort.pl script on the Xcode project to organize project references.
#

main() {
  echo "==> 📶 Sorting project files"
  sort_project
}

sort_project() {
  perl script/sort.pl mas-cli.xcodeproj/project.pbxproj
}

main
