#!/bin/bash -eu
#
# script/test
# mas
#
# Runs mas tests.
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

script/generate_version_info_for_swift

printf $'==> ✅ Testing mas %s\n' "$(script/version)"

swift test
