#!/bin/bash -e
#
# script/uninstall
# mas
#
# Removes mas from PREFIX.
#

# Override default prefix path with optional 1st arg
if test -n "${1}"; then
  PREFIX="${1}"
else
  PREFIX="$(brew --prefix)"
fi

echo "==> 🔥 Uninstalling mas from ${PREFIX}"

trash -F "${PREFIX}/bin/mas" || true
