#!/bin/bash -e
#
# script/uninstall
# mas
#
# Removes mas from a bin folder under a prefix folder, defaulting to /usr/local.
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

# Override default prefix path with optional 1st arg
prefix="${1:-"$(brew --prefix)"}"

echo "==> 🔥 Uninstalling mas from ${prefix}"

trash -F "${prefix}/bin/mas" || true
