#!/bin/bash -e
#
# script/bootstrap
# mas
#
# Installs gem tools, installs Swift dependencies via CocoaPods and sorts
# the Xcode project file references.
#

PREFIX=/usr/local

echo "==> 🔥 Installing mas"

rm -rf /usr/local/Frameworks/MasKit.framework
rm -f /usr/local/bin/mas
