#!/bin/bash -e
#
# script/version
# mas
#
# Displays the current marketing version of mas.
#

# This no longer works with MARKETING_VERSION build setting in Info.plist
# agvtool what-marketing-version -terse1

echo "1.7.0"
