#!/bin/bash -eu
#
# script/version
# mas
#
# Displays the mas version.
#

mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"

if ! cd -- "${mas_dir}"; then
  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
  exit 1
fi

version_tag="$(git describe --abbrev=0 --tags 2>/dev/null)"
printf $'%s\n' "${version_tag#v}"
