//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ISStoreAccount, NSArray, NSDictionary, NSString;

@interface ISStoreClient : NSObject <NSSecureCoding>
{
    BOOL __alwaysUseSandboxEnvironment;
    BOOL _isDaemon;
    unsigned long long _frameworkVersion;
    NSString *_identifier;
    long long _clientType;
    ISStoreAccount *_primaryAccount;
    NSString *_userAgentAppName;
    NSString *_userAgentAppVersion;
    NSString *_agentPreferencesDomain;
    NSString *_appPreferencesDomain;
    NSString *_storeFrontBagKey;
    NSArray *_productionBagURLs;
    NSArray *_sandboxBagURLs;
    NSString *_toolbarBagKey;
    long long _requiredBagType;
    NSString *_aslDomain;
    NSString *_storeURLScheme;
    NSString *_storeSecureURLScheme;
    NSString *_tempPathClientIdentifier;
    long long _mediaTypeMask;
    NSString *_pushServiceName;
    NSString *_appPath;
    NSDictionary *_daap;
    NSString *_displayUIHostID;
    NSString *_agentListenerName;
}

+ (id)knownClientWithIdentifier:(id)arg1 frameworkVersion:(id)arg2;
+ (BOOL)supportsSecureCoding;
@property BOOL isDaemon; // @synthesize isDaemon=_isDaemon;
@property(copy) NSString *agentListenerName; // @synthesize agentListenerName=_agentListenerName;
@property(copy) NSString *displayUIHostID; // @synthesize displayUIHostID=_displayUIHostID;
@property(copy) NSDictionary *daap; // @synthesize daap=_daap;
@property(copy) NSString *appPath; // @synthesize appPath=_appPath;
@property(copy) NSString *pushServiceName; // @synthesize pushServiceName=_pushServiceName;
@property long long mediaTypeMask; // @synthesize mediaTypeMask=_mediaTypeMask;
@property(copy) NSString *tempPathClientIdentifier; // @synthesize tempPathClientIdentifier=_tempPathClientIdentifier;
@property(copy) NSString *storeSecureURLScheme; // @synthesize storeSecureURLScheme=_storeSecureURLScheme;
@property(copy) NSString *storeURLScheme; // @synthesize storeURLScheme=_storeURLScheme;
@property(setter=_setAlwaysUseSandboxEnvironment:) BOOL _alwaysUseSandboxEnvironment; // @synthesize _alwaysUseSandboxEnvironment=__alwaysUseSandboxEnvironment;
@property(copy) NSString *aslDomain; // @synthesize aslDomain=_aslDomain;
@property long long requiredBagType; // @synthesize requiredBagType=_requiredBagType;
@property(copy) NSString *toolbarBagKey; // @synthesize toolbarBagKey=_toolbarBagKey;
@property(copy) NSArray *sandboxBagURLs; // @synthesize sandboxBagURLs=_sandboxBagURLs;
@property(copy) NSArray *productionBagURLs; // @synthesize productionBagURLs=_productionBagURLs;
@property(copy) NSString *storeFrontBagKey; // @synthesize storeFrontBagKey=_storeFrontBagKey;
@property(copy) NSString *appPreferencesDomain; // @synthesize appPreferencesDomain=_appPreferencesDomain;
@property(copy) NSString *agentPreferencesDomain; // @synthesize agentPreferencesDomain=_agentPreferencesDomain;
@property(copy) NSString *userAgentAppVersion; // @synthesize userAgentAppVersion=_userAgentAppVersion;
@property(copy) NSString *userAgentAppName; // @synthesize userAgentAppName=_userAgentAppName;
@property(copy) ISStoreAccount *primaryAccount; // @synthesize primaryAccount=_primaryAccount;
@property long long clientType; // @synthesize clientType=_clientType;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
@property unsigned long long frameworkVersion; // @synthesize frameworkVersion=_frameworkVersion;
//- (void).cxx_destruct;
- (BOOL)isEqualToStoreClient:(id)arg1;
- (void)_cacheKnownClient:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithApplicationPath:(id)arg1;
- (id)initWithStoreClientType:(long long)arg1;

@end

