#!/bin/zsh -Ndefgku
#
# Scripts/build
# mas
#
# Builds the Swift Package.
#

. "${0:a:h}/_setup_script"

print_header '🏗​ Building mas' "$(Scripts/version)"

Scripts/generate_package_swift "${1:-}"

swift build -c release "${@:2}"
