#!/bin/zsh -Ndefgku
#
# Scripts/build
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Builds the Swift package.
#

. "${0:A:h}/_setup_script"

print_notice '🏗​ Building' "${@}"

export -r MAS_DISTRIBUTION="${1:-}"

swift build "${@:2}"
