#!/bin/zsh -Ndefgku
#
# Scripts/format
# mas
#
# Automatically formats & fixes style violations using various tools.
#
# Please keep in sync with Scripts/lint.
#

. "${0:a:h}/_setup_script"

print_notice '🧹 Formatting' "$(Scripts/version)" "${@}"

ensure_command_available markdownlint-cli2 swiftformat swiftlint

printf -- $'--> 🕊​ SwiftFormat\n'
script -q /dev/null swiftformat --strict --markdown-files format-strict . |
 (grep -vxE '(?:\^D\x08{2})?Running SwiftFormat\.{3}\r|Reading (?:config|swift-version) file at .*|\x1b\[32mSwiftFormat completed in \d+(?:\.\d+)?s\.\x1b\[0m\r|0/\d+ files formatted\.\r' || true)

printf -- $'--> 🦅 SwiftLint\n'
swiftlint --fix --quiet --reporter relative-path

printf -- $'--> 〽️ Markdown\n'
markdownlint-cli2 --fix '**/*.md'
