#!/bin/zsh -Ndefgku
#
# Scripts/generate_manual
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Generates man page.
#

. "${0:A:h}/_setup_script"

print_notice '📖 Generating man pages for' "${@}"

export MAS_INSTALL_METHOD="${1:-}"

swift package generate-manual "${@:2}"
