#!/bin/zsh -Ndefgku
#
# Scripts/generate_manual
# mas
#
# Generate man page.
#

. "${0:a:h}/_setup_script"

print_notice '📖 Generating man pages for' "$(Scripts/version)" "${@}"

export MAS_INSTALL_METHOD="${1:-}"

swift package generate-manual "${@:2}"
