#!/bin/zsh -Ndefgku
#
# Scripts/prebuild
# mas
#
# Copyright © 2025 mas-cli. All rights reserved.
#
# Prebuilds the Swift package.
#

. "${0:A:h}/_setup_script"

print_notice '🎬 Prebuilding' "${@}"

# Generate Swift file containing build information.
# shellcheck disable=SC1102
cat <<EOF >"${1}/MAS+BuildInformation.swift"
//
// MAS+BuildInformation.swift
// mas
//
// Copyright © $(date '+%Y') mas-cli. All rights reserved.
//

extension MAS {
	static let version = "$(Scripts/version)"
	static let installMethod = "${MAS_INSTALL_METHOD:-unknown}"
	static let gitOrigin = "$(git remote get-url origin)"
	static let gitRevision = "$(git rev-parse HEAD)"
	static let swiftVersion = "$(printf %s "${${$(swift --version 2>/dev/null)#Apple Swift version }%%$'\n'*}")"
	static let swiftDriverVersion = "$(printf %s "${${$((swift --version 3>&2 2>&1 1>&3) 2>/dev/null)#swift-driver version: }% }")"
}
EOF
