#!/bin/zsh -Ndefgku
#
# Scripts/setup_xcode
# mas
#
# Sets up Xcode.
#

. "${0:a:h}/_setup_script"

print_notice '🔨 Setting up Xcode for' "${@}"

xcode_sources_dir=.swiftpm/xcode/Sources
mkdir -p "${xcode_sources_dir}"
ln -sF ../../../Sources/PrivateFrameworks "${xcode_sources_dir}/PrivateFrameworks"
