#!/bin/zsh -Ndefgku
#
# Scripts/test
# mas
#
# Runs mas tests.
#

. "${0:a:h}/_setup_script"

print_notice '🧪 Testing' "$(Scripts/version)" "${@}"

export MAS_INSTALL_METHOD=test

swift test --disable-xctest --no-parallel -q "${@}"
