#!/bin/zsh -Ndefgku
#
# Scripts/update_headers
# mas
#
# Generates headers for Apple private frameworks.
#

. "${0:a:h}/_setup_script"

ensure_command_available ipsw

cd Sources/PrivateFrameworks

for framework in *(/); do
	ipsw class-dump --headers --output . /System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_arm64e "${framework}"
done
