#!/bin/zsh -Ndefgku
#
# Scripts/update_headers
# mas
#
# Generates headers for Apple private frameworks.
#

. "${0:a:h}/_setup_script"

ensure_command_available ipsw

cd Sources/PrivateFrameworks

for framework in *(/); do
	ipsw class-dump --headers --output . /System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_arm64e "${framework}"
done

# shellcheck disable=SC1036
sed -Ei '' -- 's!^//    -!// -!g' ***/*.h(.N)
sed -Ei '' -- 's!^//  !//!g' ***/*.h(.N)
sed -Ei '' -- '/^#(define|endif|ifndef).*/d' ***/*.h(.N)
sed -Ei '' -- '/^ *\/\*.*\*\/$/d' ***/*.h(.N)
sed -Ei '' -- 's/^    /\t/g' ***/*.h(.N)
sed -Ei '' -- 's/_Bool/BOOL/g' ***/*.h(.N)
sed -Ei '' -- 's/^- \(id\)description;$/- \(nonnull NSString \*\)description;/g' ***/*.h(.N)
sed -Ei '' -- 's/^- \(void\)encodeWithCoder:\(id\)coder;$/- \(void\)encodeWithCoder:\(nullable NSCoder \*\)coder;/g' ***/*.h(.N)
sed -Ei '' -- 's/^- \(id\)initWithCoder:\(id\)coder;$/- \(nonnull instancetype\)initWithCoder:\(nullable NSCoder \*\)coder;/g' ***/*.h(.N)
sed -Ei '' -- 's/^- \(BOOL\)isEqual:\(id\)equal;$/- \(BOOL\)isEqual:\(nullable id\)object;/g' ***/*.h(.N)
sed -Ei '' -- 's/\(copy\)/\(copy, nullable\)/g' ***/*.h(.N)
sed -Ei '' -- 's/\(copy, nonatomic\)/\(copy, nonatomic, nullable\)/g' ***/*.h(.N)
sed -Ei '' -- 's/\(id\)client/\(nullable ISStoreClient \*\)client/g' ***/*.h(.N)
sed -Ei '' -- 's/\(id\)dictionary/\(nullable NSDictionary \*\)dictionary/g' ***/*.h(.N)
sed -Ei '' -- 's/\(id\)init/\(nonnull instancetype)init/g' ***/*.h(.N)
sed -Ei '' -- 's/\(retain\)/\(retain, nullable\)/g' ***/*.h(.N)
sed -Ei '' -- 's/\(retain, nonatomic\)/\(retain, nonatomic, nullable\)/g' ***/*.h(.N)
sed -Ei '' -- 's/\(id\)dsid/\(nullable NSNumber \*\)dsID/g' ***/*.h(.N)
sed -Ei '' -- 's/NSArray \*downloads/NSArray\<SSDownload \*\> \*downloads/g' ***/*.h(.N)
sed -Ei '' -- 's/\(id\)productID/\(nonnull NSNumber \*\)productID/g' ***/*.h(.N)
sed -Ei '' -- 's/- \(id\)copyWithZone:\(struct _NSZone \*\)zone;/- \(nonnull instancetype\)copyWithZone:\(nullable struct _NSZone \*\)zone;/g' ***/*.h(.N)
sed -Ei '' -- 's/\(id\)progress/\(nullable SSOperationProgress \*\)progress/g' ***/*.h(.N)
sed -Ei '' -- 's/\(id\)url/\(nullable NSURL \*\)url/g' ***/*.h(.N)
sed -Ei '' -- 's!id /\* block \*/!UnknownBlock!g' ***/*.h(.N)
